-- Phase 24F: Support-owned CSAT and quality facts. No protected-domain mutation.
CREATE TABLE IF NOT EXISTS support_csat_records (
 csat_id VARCHAR(64) NOT NULL,city_code VARCHAR(64) NOT NULL,ticket_id VARCHAR(64) NULL,conversation_id VARCHAR(64) NULL,
 requester_type VARCHAR(16) NOT NULL,requester_id VARCHAR(64) NOT NULL,score TINYINT UNSIGNED NOT NULL,comment VARCHAR(1000) NULL,
 related_worker_id VARCHAR(64) NULL,assigned_agent_admin_id VARCHAR(64) NULL,assigned_skill_group_id VARCHAR(64) NULL,
 closed_at_snapshot TIMESTAMP(3) NOT NULL,idempotency_key VARCHAR(128) NOT NULL,request_fingerprint CHAR(64) NOT NULL,
 submitted_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY(csat_id),UNIQUE KEY uq_csat_city_id(city_code,csat_id),
 UNIQUE KEY uq_csat_ticket(city_code,ticket_id),UNIQUE KEY uq_csat_conversation(city_code,conversation_id),
 UNIQUE KEY uq_csat_idempotency(city_code,requester_type,requester_id,idempotency_key),
 INDEX idx_csat_dashboard(city_code,submitted_at,csat_id),
 CONSTRAINT fk_csat_city FOREIGN KEY(city_code) REFERENCES cities(city_code),
 CONSTRAINT fk_csat_ticket FOREIGN KEY(city_code,ticket_id) REFERENCES support_tickets(city_code,ticket_id),
 CONSTRAINT fk_csat_conversation FOREIGN KEY(city_code,conversation_id) REFERENCES support_conversations(city_code,conversation_id),
 CONSTRAINT chk_csat_city CHECK(city_code<>'__global__'),CONSTRAINT chk_csat_target CHECK((ticket_id IS NULL)<>(conversation_id IS NULL)),
 CONSTRAINT chk_csat_requester CHECK(requester_type IN('customer','worker')),CONSTRAINT chk_csat_score CHECK(score BETWEEN 1 AND 5),
 CONSTRAINT chk_csat_fingerprint CHECK(request_fingerprint REGEXP '^[0-9a-f]{64}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS support_quality_rubrics (
 rubric_id VARCHAR(64) NOT NULL,city_code VARCHAR(64) NOT NULL,name VARCHAR(128) NOT NULL,description VARCHAR(1000) NULL,status VARCHAR(16) NOT NULL DEFAULT 'draft',current_version INT UNSIGNED NOT NULL DEFAULT 0,created_by_admin_id VARCHAR(64) NOT NULL,version BIGINT UNSIGNED NOT NULL DEFAULT 1,created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),PRIMARY KEY(rubric_id),UNIQUE KEY uq_rubric_city_id(city_code,rubric_id),UNIQUE KEY uq_rubric_name(city_code,name),CONSTRAINT fk_rubric_city FOREIGN KEY(city_code) REFERENCES cities(city_code),CONSTRAINT fk_rubric_admin FOREIGN KEY(created_by_admin_id) REFERENCES admin_users(id),CONSTRAINT chk_rubric_city CHECK(city_code<>'__global__'),CONSTRAINT chk_rubric_status CHECK(status IN('draft','published','archived'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS support_quality_rubric_versions (
 rubric_version_id VARCHAR(64) NOT NULL,city_code VARCHAR(64) NOT NULL,rubric_id VARCHAR(64) NOT NULL,version_number INT UNSIGNED NOT NULL,criteria_json JSON NOT NULL,maximum_score DECIMAL(8,2) NOT NULL,content_hash CHAR(64) NOT NULL,created_by_admin_id VARCHAR(64) NOT NULL,published_at TIMESTAMP(3) NULL,created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY(rubric_version_id),UNIQUE KEY uq_rubric_version_city_id(city_code,rubric_version_id),UNIQUE KEY uq_rubric_version_number(city_code,rubric_id,version_number),CONSTRAINT fk_rubric_version_parent FOREIGN KEY(city_code,rubric_id) REFERENCES support_quality_rubrics(city_code,rubric_id),CONSTRAINT chk_rubric_version_hash CHECK(content_hash REGEXP '^[0-9a-f]{64}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS support_quality_reviews (
 quality_review_id VARCHAR(64) NOT NULL,city_code VARCHAR(64) NOT NULL,ticket_id VARCHAR(64) NULL,conversation_id VARCHAR(64) NULL,reviewer_admin_id VARCHAR(64) NOT NULL,reviewed_agent_admin_id VARCHAR(64) NULL,rubric_version_id VARCHAR(64) NOT NULL,rubric_snapshot_json JSON NOT NULL,rubric_content_hash CHAR(64) NOT NULL,criterion_scores_json JSON NOT NULL,overall_score DECIMAL(5,2) NOT NULL,finding VARCHAR(4000) NULL,status VARCHAR(16) NOT NULL DEFAULT 'submitted',idempotency_key VARCHAR(128) NOT NULL,request_fingerprint CHAR(64) NOT NULL,version BIGINT UNSIGNED NOT NULL DEFAULT 1,submitted_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),active_ticket_guard VARCHAR(64) GENERATED ALWAYS AS(CASE WHEN status='submitted' THEN ticket_id ELSE NULL END) STORED,active_conversation_guard VARCHAR(64) GENERATED ALWAYS AS(CASE WHEN status='submitted' THEN conversation_id ELSE NULL END) STORED,PRIMARY KEY(quality_review_id),UNIQUE KEY uq_review_idempotency(city_code,reviewer_admin_id,idempotency_key),UNIQUE KEY uq_review_ticket(city_code,active_ticket_guard),UNIQUE KEY uq_review_conversation(city_code,active_conversation_guard),INDEX idx_review_dashboard(city_code,status,submitted_at,quality_review_id),CONSTRAINT fk_review_ticket FOREIGN KEY(city_code,ticket_id) REFERENCES support_tickets(city_code,ticket_id),CONSTRAINT fk_review_conversation FOREIGN KEY(city_code,conversation_id) REFERENCES support_conversations(city_code,conversation_id),CONSTRAINT fk_review_rubric_version FOREIGN KEY(city_code,rubric_version_id) REFERENCES support_quality_rubric_versions(city_code,rubric_version_id),CONSTRAINT chk_review_target CHECK((ticket_id IS NULL)<>(conversation_id IS NULL)),CONSTRAINT chk_review_score CHECK(overall_score BETWEEN 0 AND 100),CONSTRAINT chk_review_status CHECK(status IN('submitted','voided'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO schema_migrations(version) VALUES('053_phase24f_support_quality') ON DUPLICATE KEY UPDATE version=version;
