import { useCallback, useEffect, useState } from "react";
import type { BusinessAgreementPrice, BusinessApiCredential, BusinessClient, BusinessWebhookDelivery, BusinessWebhookSubscription, EnterpriseBillSnapshot } from "@xlb/types";
import { BUSINESS_WEBHOOK_EVENT_TYPES } from "@xlb/types";
import { ApiErrorPanel, Button, Card, EmptyState, FormField, Input, ScopeBadge, Select, StatusTag, Table } from "@xlb/ui";
import { adminOpsApi as api } from "../adminAuth";

export function EnterpriseOpsPage({initialCityCode}:{initialCityCode?:string}){
  const [cityCode,setCityCode]=useState(initialCityCode||"hangzhou");const [clients,setClients]=useState<BusinessClient[]>([]);const [selected,setSelected]=useState("");
  const [credentials,setCredentials]=useState<BusinessApiCredential[]>([]);const [agreements,setAgreements]=useState<BusinessAgreementPrice[]>([]);const [subscriptions,setSubscriptions]=useState<BusinessWebhookSubscription[]>([]);const [deliveries,setDeliveries]=useState<BusinessWebhookDelivery[]>([]);const [bills,setBills]=useState<EnterpriseBillSnapshot[]>([]);
  const [clientCode,setClientCode]=useState("ACME_HZ");const [clientName,setClientName]=useState("Acme Facilities Hangzhou");const [billingMode,setBillingMode]=useState<"single"|"monthly">("monthly");const [contactName,setContactName]=useState("Enterprise Operator");const [contactPhone,setContactPhone]=useState("13800000001");
  const [skuId,setSkuId]=useState("sku_home_daily_2h");const [unitPrice,setUnitPrice]=useState("80");const [callbackUrl,setCallbackUrl]=useState("mock://success/enterprise");const [revealed,setRevealed]=useState<{apiKey?:string;signingSecret?:string}>({});const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);
  const now=new Date();const [periodStart,setPeriodStart]=useState(new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1)).toISOString().slice(0,10));const [periodEnd,setPeriodEnd]=useState(new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,1)).toISOString().slice(0,10));

  const loadClients=useCallback(async()=>{setBusy("clients");setError(null);try{window.history.replaceState({},"",`#/enterprise?cityCode=${encodeURIComponent(cityCode)}`);const result=await api.enterprise.listClients();setClients(result.clients);if(!selected&&result.clients[0])setSelected(result.clients[0].businessClientId);}catch(err){setError(err instanceof Error?err.message:"Unable to load enterprise clients");}finally{setBusy(null);}},[cityCode,selected]);
  const loadDetail=useCallback(async()=>{if(!selected)return;setBusy("detail");setError(null);try{const [c,a,s,d,b]=await Promise.all([api.enterprise.listCredentials(selected),api.enterprise.listAgreementPrices(selected),api.enterprise.listWebhookSubscriptions(selected),api.enterprise.listWebhookDeliveries(selected),api.enterprise.listBills(selected)]);setCredentials(c.credentials);setAgreements(a.agreementPrices);setSubscriptions(s.subscriptions);setDeliveries(d.deliveries);setBills(b.bills);}catch(err){setError(err instanceof Error?err.message:"Unable to load enterprise detail");}finally{setBusy(null);}},[selected]);
  useEffect(()=>{void loadClients();},[loadClients]);useEffect(()=>{void loadDetail();},[loadDetail]);
  async function act(name:string,fn:()=>Promise<void>){setBusy(name);setError(null);try{await fn();}catch(err){setError(err instanceof Error?err.message:"Enterprise operation failed");}finally{setBusy(null);}}
  const selectedClient=clients.find(item=>item.businessClientId===selected);

  return <div style={{display:"grid",gap:16}}>
    <Card title="Enterprise Clients" actions={<ScopeBadge scope={`city: ${cityCode}`}/>}><div style={{display:"flex",gap:8,alignItems:"end",flexWrap:"wrap"}}><FormField label="City"><Input value={cityCode} onChange={e=>setCityCode(e.target.value)}/></FormField><Button onClick={()=>void loadClients()} disabled={busy!==null}>Refresh</Button><StatusTag tone="primary">API key scoped</StatusTag><StatusTag tone="warning">No payment execution</StatusTag></div></Card>
    {error&&<ApiErrorPanel title="Enterprise operation failed" detail={error}/>} 
    <Card title="Onboard client" actions={<StatusTag tone="success">real write</StatusTag>}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10}}><FormField label="Client code"><Input value={clientCode} onChange={e=>setClientCode(e.target.value)}/></FormField><FormField label="Legal/display name"><Input value={clientName} onChange={e=>setClientName(e.target.value)}/></FormField><FormField label="Billing mode"><Select value={billingMode} onChange={e=>setBillingMode(e.target.value as "single"|"monthly")}><option value="single">Single order</option><option value="monthly">Monthly</option></Select></FormField><FormField label="Primary contact"><Input value={contactName} onChange={e=>setContactName(e.target.value)}/></FormField><FormField label="Contact phone"><Input value={contactPhone} onChange={e=>setContactPhone(e.target.value)}/></FormField></div><div style={{marginTop:10}}><Button variant="primary" disabled={busy!==null} onClick={()=>void act("create-client",async()=>{const result=await api.enterprise.createClient({clientCode,name:clientName,billingMode,contactName,contactPhone});setSelected(result.client.businessClientId);await loadClients();})}>Create client</Button></div></Card>
    <Card title="Client registry" actions={<StatusTag tone="primary">{clients.length}</StatusTag>}>{clients.length===0?<EmptyState title="No enterprise clients"/>:<Table rows={clients} getRowKey={r=>r.businessClientId} columns={[{key:"code",title:"Code",render:r=>r.clientCode},{key:"name",title:"Name",render:r=>r.name},{key:"billing",title:"Billing",render:r=>r.billingMode},{key:"status",title:"Status",render:r=><StatusTag tone={r.status==="active"?"success":"warning"}>{r.status}</StatusTag>},{key:"open",title:"Open",render:r=><Button onClick={()=>setSelected(r.businessClientId)}>Manage</Button>}]}/>}</Card>
    {selectedClient&&<>
      <Card title={`Credentials · ${selectedClient.clientCode}`} actions={<StatusTag tone="warning">secret shown once</StatusTag>}><div style={{display:"flex",gap:8,flexWrap:"wrap",alignItems:"center"}}><Button variant="primary" disabled={busy!==null} onClick={()=>void act("credential",async()=>{const result=await api.enterprise.createCredential(selected,{name:"Primary integration",scopes:["enterprise:orders:read","enterprise:orders:write","enterprise:webhooks:read","enterprise:webhooks:write"]});setRevealed(v=>({...v,apiKey:result.apiKey}));await loadDetail();})}>Issue API key</Button><Button disabled={busy!==null} onClick={()=>void act("client-status",async()=>{await api.enterprise.updateClientStatus(selected,selectedClient.status==="active"?"suspended":"active");await loadClients();})}>{selectedClient.status==="active"?"Suspend client":"Activate client"}</Button>{revealed.apiKey&&<code style={{overflowWrap:"anywhere"}}>{revealed.apiKey}</code>}</div>{credentials.length>0&&<Table rows={credentials} getRowKey={r=>r.credentialId} columns={[{key:"name",title:"Name",render:r=>r.name},{key:"prefix",title:"Prefix",render:r=>r.keyPrefix},{key:"scopes",title:"Scopes",render:r=>r.scopes.join(", ")},{key:"status",title:"Status",render:r=>r.status},{key:"revoke",title:"Revoke",render:r=><Button disabled={r.status!=="active"||busy!==null} onClick={()=>void act(r.credentialId,async()=>{await api.enterprise.revokeCredential(selected,r.credentialId);await loadDetail();})}>Revoke</Button>}]}/>}</Card>
      <Card title="Agreement price"><div style={{display:"flex",gap:8,alignItems:"end",flexWrap:"wrap"}}><FormField label="SKU"><Input value={skuId} onChange={e=>setSkuId(e.target.value)}/></FormField><FormField label="Unit price CNY"><Input value={unitPrice} onChange={e=>setUnitPrice(e.target.value)}/></FormField><Button variant="primary" disabled={busy!==null} onClick={()=>void act("price",async()=>{await api.enterprise.upsertAgreementPrice(selected,{skuId,unitPrice:Number(unitPrice),effectiveFrom:new Date().toISOString()});await loadDetail();})}>Save agreement</Button></div>{agreements.length>0&&<Table rows={agreements} getRowKey={r=>r.agreementPriceId} columns={[{key:"sku",title:"SKU",render:r=>r.skuId},{key:"price",title:"Unit price",render:r=>`CNY ${r.unitPrice.toFixed(2)}`},{key:"status",title:"Status",render:r=>r.status}]}/>}</Card>
      <Card title="Webhook subscriptions" actions={<StatusTag tone="primary">signed HMAC-SHA256</StatusTag>}><div style={{display:"flex",gap:8,alignItems:"end",flexWrap:"wrap"}}><FormField label="Callback URL"><Input value={callbackUrl} onChange={e=>setCallbackUrl(e.target.value)} style={{minWidth:300}}/></FormField><Button variant="primary" disabled={busy!==null} onClick={()=>void act("subscription",async()=>{const result=await api.enterprise.createWebhookSubscription(selected,{callbackUrl,eventTypes:[...BUSINESS_WEBHOOK_EVENT_TYPES]});setRevealed(v=>({...v,signingSecret:result.signingSecret}));await loadDetail();})}>Create subscription</Button><Button disabled={busy!==null} onClick={()=>void act("run",async()=>{await api.enterprise.runWebhooks();await loadDetail();})}>Run delivery</Button></div>{revealed.signingSecret&&<p><strong>Signing secret:</strong> <code>{revealed.signingSecret}</code></p>}{subscriptions.length>0&&<Table rows={subscriptions} getRowKey={r=>r.subscriptionId} columns={[{key:"url",title:"Callback",render:r=>r.callbackUrl},{key:"events",title:"Events",render:r=>String(r.eventTypes.length)},{key:"secret",title:"Secret",render:r=>`••••${r.signingSecretLast4}`},{key:"status",title:"Status",render:r=>r.status},{key:"toggle",title:"Control",render:r=><Button disabled={busy!==null} onClick={()=>void act(r.subscriptionId,async()=>{await api.enterprise.updateWebhookSubscriptionStatus(selected,r.subscriptionId,r.status==="active"?"paused":"active");await loadDetail();})}>{r.status==="active"?"Pause":"Activate"}</Button>}]}/>}</Card>
      <Card title="Delivery log" actions={<StatusTag tone="primary">idempotent + retryable</StatusTag>}>{deliveries.length===0?<EmptyState title="No deliveries yet"/>:<Table rows={deliveries} getRowKey={r=>r.deliveryId} columns={[{key:"event",title:"Event",render:r=>r.eventType},{key:"status",title:"Status",render:r=><StatusTag tone={r.status==="delivered"?"success":"warning"}>{r.status}</StatusTag>},{key:"attempt",title:"Attempts",render:r=>`${r.attemptCount}/${r.maxAttempts}`},{key:"provider",title:"Provider",render:r=>r.providerEnvelope?.providerStatus||"pending"},{key:"retry",title:"Retry",render:r=><Button disabled={!(["retry_wait","dead_letter"] as string[]).includes(r.status)||busy!==null} onClick={()=>void act(r.deliveryId,async()=>{await api.enterprise.retryWebhookDelivery(selected,r.deliveryId);await api.enterprise.runWebhooks();await loadDetail();})}>Retry</Button>}]}/>}</Card>
      <Card title="Monthly bill snapshots" actions={<StatusTag tone="warning">non-executing</StatusTag>}><div style={{display:"flex",gap:8,alignItems:"end",flexWrap:"wrap"}}><FormField label="Period start"><Input type="date" value={periodStart} onChange={e=>setPeriodStart(e.target.value)}/></FormField><FormField label="Period end"><Input type="date" value={periodEnd} onChange={e=>setPeriodEnd(e.target.value)}/></FormField><Button variant="primary" disabled={busy!==null||selectedClient.billingMode!=="monthly"} onClick={()=>void act("bill",async()=>{await api.enterprise.createBill(selected,{periodStart:new Date(`${periodStart}T00:00:00Z`).toISOString(),periodEnd:new Date(`${periodEnd}T00:00:00Z`).toISOString()});await loadDetail();})}>Create snapshot</Button></div>{bills.length>0&&<Table rows={bills} getRowKey={r=>r.billId} columns={[{key:"period",title:"Period",render:r=>`${r.periodStart.slice(0,10)} → ${r.periodEnd.slice(0,10)}`},{key:"orders",title:"Orders",render:r=>String(r.orderCount)},{key:"total",title:"Total",render:r=>`CNY ${r.totalAmount.toFixed(2)}`},{key:"status",title:"Status",render:r=>r.status},{key:"issue",title:"Issue",render:r=><Button disabled={r.status!=="draft"||busy!==null} onClick={()=>void act(r.billId,async()=>{await api.enterprise.issueBill(selected,r.billId);await loadDetail();})}>Issue</Button>}]}/>}</Card>
    </>}
  </div>;
}
