import { useState, useEffect } from "react";
import { settlementApi, createApiClient } from "@xlb/api-client";
import { API_BASE } from "../apiBase";
import { Button, Card, EmptyState, ErrorState, LoadingState, PriceText, StatusTag, Table, Timeline } from "@xlb/ui";

const client = createApiClient({ baseUrl: API_BASE, headers: { "x-xlb-app-type": "admin", "x-xlb-role": "operator" } });
const api = settlementApi.create(client);

interface DetailData {
  statement: {
    statementId: string; cityCode: string; workerId: string;
    settlementBatchId: string; queueId: string; settlementPayableId: string;
    currency: string; grossAmount: number; platformFeeAmount: number;
    workerReceivableAmount: number; itemCount: number;
    status: string; generatedAt: string; generatedBy: string;
    createdAt: string; updatedAt: string;
  } | null;
  review: {
    reviewId: string; decision: string; reviewNote: string | null;
    reviewedAt: string; reviewedBy: string;
  } | null;
  export: {
    exportId: string; contentHash: string;
    exportedAt: string; exportedBy: string; outboxEventId: string | null;
  } | null;
  exportedOutboxEvent: {
    eventId: string; eventType: string;
    status: string; publishedAt: string | null;
  } | null;
}

interface Props {
  statementId: string;
  onBack: () => void;
  cityCode?: string;
  onNavigateToExports?: (extra?: Record<string, string>) => void;
}

export function SettlementStatementDetailPage({ statementId, onBack, cityCode, onNavigateToExports }: Props) {
  const [data, setData] = useState<DetailData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError(null);
    api.getStatementAuditDetail(statementId)
      .then((res: unknown) => {
        if (cancelled) return;
        const r = res as { ok: boolean };
        if (r.ok) {
          setData(res as DetailData);
        } else {
          setError("Statement not found");
        }
      })
      .catch((e: unknown) => {
        if (!cancelled) setError(String(e));
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => { cancelled = true; };
  }, [statementId]);

  if (loading) return <LoadingState title="Loading statement detail..." description="Reading statement, review, export and outbox records." />;
  if (error) return <ErrorState title="Error" description={error} action={<Button onClick={onBack}>← Back to Console</Button>} />;
  if (!data) return <EmptyState title="No detail data" action={<Button onClick={onBack}>← Back to Console</Button>} />;

  const { statement, review } = data;
  const exportRecord = data.export;
  const outboxEvent = data.exportedOutboxEvent;

  return (
    <div style={{ display: "grid", gap: 16 }}>
      <Card
        title="Statement Detail"
        actions={
          <>
            {cityCode && <StatusTag tone="primary">city_scope: {cityCode}</StatusTag>}
            {statement?.status && <StatusTag tone="success">{statement.status}</StatusTag>}
          </>
        }
      >
        <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
          <Button onClick={onBack}>← Back to Console</Button>
          {onNavigateToExports && cityCode && (
            <Button onClick={() => onNavigateToExports({ statementId, cityCode })}>
              View Exports for {cityCode}
            </Button>
          )}
        </div>
      </Card>

      <Card title="Audit Timeline">
        <Timeline
          items={[
            { key: "generated", title: "Generated", description: statement?.generatedAt ?? "No statement record" },
            { key: "review", title: "Review", description: review ? `${review.decision} by ${review.reviewedBy}` : "No review yet" },
            { key: "export", title: "Export Record", description: exportRecord ? exportRecord.exportedAt : "No export yet" },
            { key: "outbox", title: "Outbox Event", description: outboxEvent ? outboxEvent.status : "No outbox event" },
          ]}
        />
      </Card>

      {statement && (
        <Card title="Statement">
          <Table
            rows={[
              ["Statement ID", statement.statementId],
              ["City", statement.cityCode],
              ["Worker", statement.workerId],
              ["Status", <StatusTag tone="success">{statement.status}</StatusTag>],
              ["Currency", statement.currency],
              ["Gross Amount", <PriceText amount={statement.grossAmount} currency={statement.currency} />],
              ["Platform Fee", <PriceText amount={statement.platformFeeAmount} currency={statement.currency} />],
              ["Worker Receivable", <PriceText amount={statement.workerReceivableAmount} currency={statement.currency} />],
              ["Item Count", statement.itemCount],
              ["Generated At", statement.generatedAt],
              ["Generated By", statement.generatedBy],
            ]}
            getRowKey={(row) => String(row[0])}
            columns={[
              { key: "field", title: "Field", render: (row) => row[0], width: 220 },
              { key: "value", title: "Value", render: (row) => row[1] },
            ]}
          />
        </Card>
      )}

      {review && (
        <Card title="Review" actions={<StatusTag tone="success">reviewed</StatusTag>}>
          <Table
            rows={[
              ["Decision", review.decision],
              ...(review.reviewNote ? [["Note", review.reviewNote] as [string, string]] : []),
              ["Reviewed At", review.reviewedAt],
              ["Reviewed By", review.reviewedBy],
            ]}
            getRowKey={(row) => String(row[0])}
            columns={[
              { key: "field", title: "Field", render: (row) => row[0], width: 220 },
              { key: "value", title: "Value", render: (row) => row[1] },
            ]}
          />
        </Card>
      )}
      {!review && (
        <Card title="Review"><EmptyState title="No review yet" /></Card>
      )}

      {exportRecord && (
        <Card title="Export Record" actions={<StatusTag tone="success">recorded</StatusTag>}>
          <Table
            rows={[
              ["Export ID", exportRecord.exportId],
              ["Content Hash", exportRecord.contentHash],
              ["Exported At", exportRecord.exportedAt],
              ["Exported By", exportRecord.exportedBy],
              ...(exportRecord.outboxEventId ? [["Outbox Event", exportRecord.outboxEventId] as [string, string]] : []),
            ]}
            getRowKey={(row) => String(row[0])}
            columns={[
              { key: "field", title: "Field", render: (row) => row[0], width: 220 },
              { key: "value", title: "Value", render: (row) => row[1] },
            ]}
          />
        </Card>
      )}
      {!exportRecord && (
        <Card title="Export Record"><EmptyState title="No export yet" /></Card>
      )}

      {outboxEvent && (
        <Card title="Outbox Event" actions={<StatusTag tone="primary">{outboxEvent.status}</StatusTag>}>
          <Table
            rows={[
              ["Event ID", outboxEvent.eventId],
              ["Type", outboxEvent.eventType],
              ["Status", outboxEvent.status],
              ...(outboxEvent.publishedAt ? [["Published At", outboxEvent.publishedAt] as [string, string]] : []),
            ]}
            getRowKey={(row) => String(row[0])}
            columns={[
              { key: "field", title: "Field", render: (row) => row[0], width: 220 },
              { key: "value", title: "Value", render: (row) => row[1] },
            ]}
          />
        </Card>
      )}
      {!outboxEvent && (
        <Card title="Outbox Event"><EmptyState title="No outbox event" /></Card>
      )}

      <div><Button onClick={onBack}>← Back to Console</Button></div>
    </div>
  );
}
