import { useState, useEffect } from "react";
import { settlementApi, createApiClient } from "@xlb/api-client";

const client = createApiClient({ baseUrl: "http://localhost:3000", headers: { "x-xlb-app-type": "admin", "x-xlb-role": "operator" } });
const api = settlementApi.create(client);

interface DetailData {
  statement: {
    statementId: string; cityCode: string; workerId: string;
    settlementBatchId: string; queueId: string; settlementPayableId: string;
    currency: string; grossAmount: number; platformFeeAmount: number;
    workerReceivableAmount: number; itemCount: number;
    status: string; generatedAt: string; generatedBy: string;
    createdAt: string; updatedAt: string;
  } | null;
  review: {
    reviewId: string; decision: string; reviewNote: string | null;
    reviewedAt: string; reviewedBy: string;
  } | null;
  export: {
    exportId: string; contentHash: string;
    exportedAt: string; exportedBy: string; outboxEventId: string | null;
  } | null;
  exportedOutboxEvent: {
    eventId: string; eventType: string;
    status: string; publishedAt: string | null;
  } | null;
}

interface Props {
  statementId: string;
  onBack: () => void;
  cityCode?: string;
  onNavigateToExports?: (extra?: Record<string, string>) => void;
}

export function SettlementStatementDetailPage({ statementId, onBack, cityCode, onNavigateToExports }: Props) {
  const [data, setData] = useState<DetailData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError(null);
    api.getStatementAuditDetail(statementId)
      .then((res: unknown) => {
        if (cancelled) return;
        const r = res as { ok: boolean };
        if (r.ok) {
          setData(res as DetailData);
        } else {
          setError("Statement not found");
        }
      })
      .catch((e: unknown) => {
        if (!cancelled) setError(String(e));
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => { cancelled = true; };
  }, [statementId]);

  if (loading) return <div style={{ padding: 24 }}><p>Loading statement detail...</p></div>;
  if (error) return <div style={{ padding: 24 }}><p style={{ color: "red" }}>Error: {error}</p></div>;
  if (!data) return <div style={{ padding: 24 }}><p>No detail data</p></div>;

  const { statement, review } = data;
  const exportRecord = data.export;
  const outboxEvent = data.exportedOutboxEvent;

  return (
    <div style={{ padding: 24 }}>
      <button onClick={onBack}>← Back to Console</button>
      <h1>Statement Detail</h1>

      {onNavigateToExports && cityCode && (
        <p><button onClick={() => onNavigateToExports({ statementId, cityCode })}>
          View Exports for {cityCode}</button></p>
      )}

      {statement && (
        <section>
          <h2>Statement</h2>
          <table>
            <tbody>
              <tr><td>Statement ID</td><td>{statement.statementId}</td></tr>
              <tr><td>City</td><td>{statement.cityCode}</td></tr>
              <tr><td>Worker</td><td>{statement.workerId}</td></tr>
              <tr><td>Status</td><td>{statement.status}</td></tr>
              <tr><td>Currency</td><td>{statement.currency}</td></tr>
              <tr><td>Gross Amount</td><td>{statement.grossAmount}</td></tr>
              <tr><td>Platform Fee</td><td>{statement.platformFeeAmount}</td></tr>
              <tr><td>Worker Receivable</td><td>{statement.workerReceivableAmount}</td></tr>
              <tr><td>Item Count</td><td>{statement.itemCount}</td></tr>
              <tr><td>Generated At</td><td>{statement.generatedAt}</td></tr>
              <tr><td>Generated By</td><td>{statement.generatedBy}</td></tr>
            </tbody>
          </table>
        </section>
      )}

      {review && (
        <section>
          <h2>Review</h2>
          <table>
            <tbody>
              <tr><td>Decision</td><td>{review.decision}</td></tr>
              {review.reviewNote && <tr><td>Note</td><td>{review.reviewNote}</td></tr>}
              <tr><td>Reviewed At</td><td>{review.reviewedAt}</td></tr>
              <tr><td>Reviewed By</td><td>{review.reviewedBy}</td></tr>
            </tbody>
          </table>
        </section>
      )}
      {!review && (
        <section><h2>Review</h2><p>No review yet</p></section>
      )}

      {exportRecord && (
        <section>
          <h2>Export Record</h2>
          <table>
            <tbody>
              <tr><td>Export ID</td><td>{exportRecord.exportId}</td></tr>
              <tr><td>Content Hash</td><td>{exportRecord.contentHash}</td></tr>
              <tr><td>Exported At</td><td>{exportRecord.exportedAt}</td></tr>
              <tr><td>Exported By</td><td>{exportRecord.exportedBy}</td></tr>
              {exportRecord.outboxEventId && <tr><td>Outbox Event</td><td>{exportRecord.outboxEventId}</td></tr>}
            </tbody>
          </table>
        </section>
      )}
      {!exportRecord && (
        <section><h2>Export Record</h2><p>No export yet</p></section>
      )}

      {outboxEvent && (
        <section>
          <h2>Outbox Event</h2>
          <table>
            <tbody>
              <tr><td>Event ID</td><td>{outboxEvent.eventId}</td></tr>
              <tr><td>Type</td><td>{outboxEvent.eventType}</td></tr>
              <tr><td>Status</td><td>{outboxEvent.status}</td></tr>
              {outboxEvent.publishedAt && <tr><td>Published At</td><td>{outboxEvent.publishedAt}</td></tr>}
            </tbody>
          </table>
        </section>
      )}
      {!outboxEvent && (
        <section><h2>Outbox Event</h2><p>No outbox event</p></section>
      )}

      <p><button onClick={onBack}>← Back to Console</button></p>
    </div>
  );
}