import { useCallback, useEffect, useMemo, useReducer, useState } from "react";
import type { AdminAddSupportTicketCommentRequest, AssignSupportTicketRequest, CloseSupportTicketRequest, EscalateSupportTicketRequest, ResolveSupportTicketRequest, SupportTicketDetailResponse, SupportTicketListFilters, SupportTicketListResponse, SupportTicketMutationResponse, SupportTicketPriority, SupportTicketSource, SupportTicketStatus, SupportTicketType } from "@xlb/types";
import { ApiErrorPanel, Button, Card, EmptyState, FormField, Input, LoadingState, ScopeBadge, Select, StatusTag, Table, Textarea } from "@xlb/ui";
import { adminOpsApi as api } from "../adminAuth";
import { initialAdminSupportUiState, adminSupportUiReducer } from "../features/support/reducer";
import { SupportRoutingConfigPage } from "./SupportRoutingConfigPage";

const requestKey = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const tone = (status: SupportTicketStatus) => status === "resolved" || status === "closed" ? "success" : status === "escalated" ? "danger" : status === "processing" ? "primary" : "warning";

export function SupportTicketsPage({ initialCityCode }: { initialCityCode?: string }) {
  const [ui, dispatch] = useReducer(adminSupportUiReducer, initialAdminSupportUiState);
  const [cityCode, setCityCode] = useState(initialCityCode || "hangzhou");
  const [tickets, setTickets] = useState<SupportTicketListResponse["tickets"]>([]);
  const [detail, setDetail] = useState<SupportTicketDetailResponse["detail"] | null>(null);
  const [status, setStatus] = useState<SupportTicketStatus | "">(""); const [priority, setPriority] = useState<SupportTicketPriority | "">("");
  const [source, setSource] = useState<SupportTicketSource | "">(""); const [type, setType] = useState<SupportTicketType | "">("");
  const [assignedAgentId, setAssignedAgentId] = useState(""); const [comment, setComment] = useState("");
  const [commentVisibility, setCommentVisibility] = useState<AdminAddSupportTicketCommentRequest["visibility"]>("all");
  const [reason, setReason] = useState(""); const [resolutionCode, setResolutionCode] = useState("answered"); const [resolutionNote, setResolutionNote] = useState("");
  const [showConfiguration, setShowConfiguration] = useState(false);
  const filters = useMemo<SupportTicketListFilters>(() => ({ status: status || undefined, priority: priority || undefined, source: source || undefined, type: type || undefined, limit: 100 }), [priority, source, status, type]);
  const load = useCallback(async () => { dispatch({ type: "started", operation: "list" }); try { window.history.replaceState({}, "", `#/support?cityCode=${encodeURIComponent(cityCode)}`); const result = await api.listSupportTickets(filters); setTickets(result.tickets); dispatch({ type: "succeeded" }); } catch (error) { dispatch({ type: "failed", message: error instanceof Error ? error.message : "Unable to load support queue" }); } }, [cityCode, filters]);
  const open = useCallback(async (ticketId: string) => { dispatch({ type: "started", operation: `detail:${ticketId}` }); try { const result = await api.getSupportTicket(ticketId); setDetail(result.detail); setAssignedAgentId(result.detail.ticket.assignedAgentId || ""); dispatch({ type: "succeeded" }); } catch (error) { dispatch({ type: "failed", message: error instanceof Error ? error.message : "Unable to load ticket detail" }); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function mutate(label: string, action: (ticketId: string, version: number) => Promise<SupportTicketMutationResponse>) { if (!detail) return; const id = detail.ticket.ticketId; dispatch({ type: "started", operation: label }); try { await action(id, detail.ticket.version); const [list, selected] = await Promise.all([api.listSupportTickets(filters), api.getSupportTicket(id)]); setTickets(list.tickets); setDetail(selected.detail); dispatch({ type: "succeeded", message: `${label} completed` }); } catch (error) { dispatch({ type: "failed", message: error instanceof Error ? error.message : `${label} failed` }); } }
  const busy = ui.busy !== null;
  return <div style={{ display: "grid", gap: 16 }}>
    <Card title="Support routing and SLA"><Button onClick={() => setShowConfiguration(value => !value)}>{showConfiguration ? "Close routing configuration" : "Open routing configuration"}</Button></Card>
    {showConfiguration && <SupportRoutingConfigPage cityCode={cityCode} />}
    <Card title="Support Ticket Queue" actions={<ScopeBadge scope={`city: ${cityCode}`} />}><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(170px,1fr))", gap: 10 }}>
      <FormField label="City"><Input value={cityCode} onChange={event => setCityCode(event.target.value)} /></FormField>
      <FormField label="Status"><Select value={status} onChange={event => setStatus(event.target.value as SupportTicketStatus | "")}><option value="">All</option><option value="open">Open</option><option value="processing">Processing</option><option value="waiting_requester">Waiting requester</option><option value="escalated">Escalated</option><option value="resolved">Resolved</option><option value="closed">Closed</option></Select></FormField>
      <FormField label="Priority"><Select value={priority} onChange={event => setPriority(event.target.value as SupportTicketPriority | "")}><option value="">All</option><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option><option value="critical">Critical</option></Select></FormField>
      <FormField label="Source"><Select value={source} onChange={event => setSource(event.target.value as SupportTicketSource | "")}><option value="">All</option><option value="customer">Customer</option><option value="worker">Worker</option><option value="enterprise">Enterprise</option><option value="admin">Admin</option></Select></FormField>
      <FormField label="Type"><Select value={type} onChange={event => setType(event.target.value as SupportTicketType | "")}><option value="">All</option><option value="order_question">Order question</option><option value="order_dispute">Order dispute</option><option value="service_complaint">Service complaint</option><option value="withdrawal_issue">Withdrawal issue</option><option value="account_issue">Account issue</option><option value="safety">Safety</option><option value="other">Other</option></Select></FormField>
    </div><div style={{ marginTop: 10 }}><Button variant="primary" disabled={busy} onClick={() => void load()}>Refresh queue</Button></div></Card>
    {ui.error && <ApiErrorPanel title="Support operation failed" detail={ui.error} />}{ui.notice && <Card title="Updated"><p style={{ margin: 0 }}>{ui.notice}</p></Card>}
    <Card title="Tickets" actions={<StatusTag tone="muted">{tickets.length}</StatusTag>}>{ui.busy === "list" && tickets.length === 0 ? <LoadingState title="Loading support queue" /> : tickets.length === 0 ? <EmptyState title="No tickets match the filters" /> : <Table rows={tickets} getRowKey={row => row.ticketId} columns={[
      { key: "subject", title: "Subject", render: row => row.subject }, { key: "status", title: "Status", render: row => <StatusTag tone={tone(row.status)}>{row.status}</StatusTag> }, { key: "priority", title: "Priority", render: row => row.priority }, { key: "source", title: "Source", render: row => row.source }, { key: "type", title: "Type", render: row => row.type }, { key: "agent", title: "Assigned agent", render: row => row.assignedAgentId || "Unassigned" }, { key: "group", title: "Skill group", render: row => row.assignedSkillGroupId || "-" }, { key: "open", title: "", render: row => <Button disabled={busy} onClick={() => void open(row.ticketId)}>Open</Button> }
    ]} />}</Card>
    {detail && <Card title={`Ticket · ${detail.ticket.subject}`} actions={<StatusTag tone={tone(detail.ticket.status)}>{detail.ticket.status}</StatusTag>}><div style={{ display: "grid", gap: 12 }}>
      <p style={{ margin: 0 }}>{detail.ticket.description}</p><small>Requester: {detail.ticket.source} / {detail.ticket.requesterId} · Type: {detail.ticket.type} · Priority: {detail.ticket.priority} · Version: {detail.ticket.version}</small>
      {detail.ticket.linkedAftersaleComplaintId && <Card title="Linked aftersale complaint"><p style={{ margin: 0 }}><strong>{detail.ticket.linkedAftersaleComplaintId}</strong> · Read-only link. Complaint resolution, liability, repair and compensation remain in Aftersale Operations.</p></Card>}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(240px,1fr))", gap: 10 }}><FormField label="Assigned agent ID"><Input value={assignedAgentId} onChange={event => setAssignedAgentId(event.target.value)} /></FormField><Button disabled={busy || !assignedAgentId.trim() || detail.ticket.status === "closed"} onClick={() => void mutate("assign", (id, version) => api.assignSupportTicket(id, { assignedAgentId: assignedAgentId.trim(), expectedVersion: version, idempotencyKey: requestKey("assign") } satisfies AssignSupportTicketRequest))}>Assign</Button></div>
      <FormField label="Comment"><Textarea value={comment} onChange={event => setComment(event.target.value)} /></FormField><FormField label="Visibility"><Select value={commentVisibility} onChange={event => setCommentVisibility(event.target.value as AdminAddSupportTicketCommentRequest["visibility"])}><option value="all">Requester visible</option><option value="internal">Internal only</option></Select></FormField><Button variant="primary" disabled={busy || !comment.trim() || detail.ticket.status === "closed"} onClick={() => void mutate("comment", id => api.addSupportTicketComment(id, { content: comment.trim(), visibility: commentVisibility, idempotencyKey: requestKey("comment") }).then(result => { setComment(""); return result; }))}>Add comment</Button>
      <FormField label="Escalation / close reason"><Textarea value={reason} onChange={event => setReason(event.target.value)} /></FormField><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><Button disabled={busy || !reason.trim() || detail.ticket.status === "closed"} onClick={() => void mutate("escalate", (id, version) => api.escalateSupportTicket(id, { reason: reason.trim(), expectedVersion: version, idempotencyKey: requestKey("escalate") } satisfies EscalateSupportTicketRequest))}>Escalate</Button><Button disabled={busy || detail.ticket.status !== "resolved"} onClick={() => void mutate("close", (id, version) => api.closeSupportTicket(id, { reason: reason.trim() || undefined, expectedVersion: version, idempotencyKey: requestKey("close") } satisfies CloseSupportTicketRequest))}>Close</Button></div>
      <FormField label="Resolution code"><Input value={resolutionCode} onChange={event => setResolutionCode(event.target.value)} /></FormField><FormField label="Resolution note"><Textarea value={resolutionNote} onChange={event => setResolutionNote(event.target.value)} /></FormField><Button variant="primary" disabled={busy || !resolutionCode.trim() || detail.ticket.status === "resolved" || detail.ticket.status === "closed"} onClick={() => void mutate("resolve", (id, version) => api.resolveSupportTicket(id, { resolutionCode: resolutionCode.trim(), resolutionNote: resolutionNote.trim() || undefined, expectedVersion: version, idempotencyKey: requestKey("resolve") } satisfies ResolveSupportTicketRequest))}>Resolve</Button>
      <Card title="Timeline">{detail.events.length === 0 ? <EmptyState title="No events" /> : detail.events.map(event => <div key={event.ticketEventId} style={{ borderBottom: "1px solid #e5e7eb", padding: "8px 0" }}><strong>{event.eventType}</strong> · {event.actorType}<p style={{ margin: "3px 0" }}>{event.content || "State transition"}</p><small>{event.visibility} · {event.createdAt}</small></div>)}</Card>
    </div></Card>}
  </div>;
}
