import { useCallback, useEffect, useMemo, useReducer, useState } from "react";
import type { AdminAddSupportTicketCommentRequest, AssignSupportTicketRequest, ClaimSupportTicketRequest, CloseSupportTicketRequest, EscalateSupportTicketRequest, ResolveSupportTicketRequest, SupportBotRun, SupportConversation, SupportConversationDetailResponse, SupportTicket, SupportTicketDetailResponse, SupportTicketListFilters, SupportTicketListResponse, SupportTicketMutationResponse, SupportTicketPriority, SupportTicketSource, SupportTicketStatus, SupportTicketType, SupportTicketWorkbenchView } from "@xlb/types";
import { ApiErrorPanel, Button, Card, EmptyState, FormField, Input, LoadingState, ScopeBadge, Select, StatusTag, Table, Textarea } from "@xlb/ui";
import { adminOpsApi as api } from "../adminAuth";
import { initialAdminSupportUiState, adminSupportUiReducer } from "../features/support/reducer";
import { SupportRoutingConfigPage } from "./SupportRoutingConfigPage";
import { SupportKnowledgeBasePage } from "./SupportKnowledgeBasePage";
import { businessLabel, cityLabel, formatDateTime, presentFailure, statusLabel, statusTone, useOnlineStatus } from "../operationsPresentation";
import "./operations-workbench.css";
import "./mobile-ops.css";

const requestKey = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const tone = (status: SupportTicketStatus) => status === "resolved" || status === "closed" ? "success" : status === "escalated" ? "danger" : status === "processing" ? "primary" : "warning";
const nearDueWindowMs = 30 * 60 * 1000;

function effectiveSlaDueAt(ticket: SupportTicket): string | null {
  return ticket.firstRespondedAt
    ? ticket.slaResolutionDueAt
    : ticket.slaFirstResponseDueAt || ticket.slaResolutionDueAt;
}

function slaState(ticket: SupportTicket, now = Date.now()): { label: string; tone: "success" | "warning" | "danger" | "muted" } {
  const dueAt = effectiveSlaDueAt(ticket);
  if (!dueAt) return { label: "未配置时限", tone: "muted" };
  const remaining = new Date(dueAt).getTime() - now;
  if (remaining <= 0) return { label: `已超时 ${Math.ceil(Math.abs(remaining) / 60000)} 分钟`, tone: "danger" };
  if (remaining <= nearDueWindowMs) return { label: `剩余 ${Math.ceil(remaining / 60000)} 分钟`, tone: "warning" };
  return { label: `剩余 ${Math.ceil(remaining / 60000)} 分钟`, tone: "success" };
}

const supportFailure = (error: unknown, subject: string) => {
  const failure = presentFailure(error, subject);
  return `${failure.title}：${failure.detail}`;
};

function initialWorkbenchView(): SupportTicketWorkbenchView {
  return typeof window !== "undefined" && window.localStorage.getItem("xlb.admin.role") === "admin"
    ? "all"
    : "mine";
}

export function SupportTicketsPage({ initialCityCode }: { initialCityCode?: string }) {
  const online = useOnlineStatus();
  const [ui, dispatch] = useReducer(adminSupportUiReducer, initialAdminSupportUiState);
  const [cityCode, setCityCode] = useState(initialCityCode || "hangzhou");
  const [tickets, setTickets] = useState<SupportTicketListResponse["tickets"]>([]);
  const [nextCursor, setNextCursor] = useState<string | null>(null);
  const [detail, setDetail] = useState<SupportTicketDetailResponse["detail"] | null>(null);
  const [status, setStatus] = useState<SupportTicketStatus | "">(""); const [priority, setPriority] = useState<SupportTicketPriority | "">("");
  const [source, setSource] = useState<SupportTicketSource | "">(""); const [type, setType] = useState<SupportTicketType | "">("");
  const [assignedAgentId, setAssignedAgentId] = useState(""); const [comment, setComment] = useState("");
  const [commentVisibility, setCommentVisibility] = useState<AdminAddSupportTicketCommentRequest["visibility"]>("all");
  const [reason, setReason] = useState(""); const [resolutionCode, setResolutionCode] = useState(""); const [resolutionNote, setResolutionNote] = useState("");
  const [showConfiguration, setShowConfiguration] = useState(false);
  const [showKnowledgeBase,setShowKnowledgeBase]=useState(false);
  const [workbenchView, setWorkbenchView] = useState<SupportTicketWorkbenchView>(initialWorkbenchView);
  const [conversations, setConversations] = useState<SupportConversation[]>([]); const [conversationDetail, setConversationDetail] = useState<SupportConversationDetailResponse | null>(null); const [conversationText, setConversationText] = useState(""); const [transferAgentId, setTransferAgentId] = useState("");
  const [botRun,setBotRun]=useState<SupportBotRun|null>(null);
  const filters = useMemo<SupportTicketListFilters>(() => ({ status: status || undefined, priority: priority || undefined, source: source || undefined, type: type || undefined, view: workbenchView, sort: "sla_due", limit: 100 }), [priority, source, status, type, workbenchView]);
  const load = useCallback(async () => { dispatch({ type: "started", operation: "list" }); try { window.history.replaceState({}, "", `#/support?cityCode=${encodeURIComponent(cityCode)}`); const result = await api.listSupportTickets(filters); setTickets(result.tickets); setNextCursor(result.nextCursor); dispatch({ type: "succeeded" }); } catch (error) { const message = supportFailure(error, "客服队列"); if (message.startsWith("无权访问")) { setTickets([]); setDetail(null); } dispatch({ type: "failed", message }); } }, [cityCode, filters]);
  const loadMore = useCallback(async () => { if (!nextCursor) return; dispatch({ type: "started", operation: "list-more" }); try { const result = await api.listSupportTickets({ ...filters, cursor: nextCursor }); setTickets(current => [...current, ...result.tickets]); setNextCursor(result.nextCursor); dispatch({ type: "succeeded" }); } catch (error) { dispatch({ type: "failed", message: supportFailure(error, "更多客服工单") }); } }, [filters, nextCursor]);
  const open = useCallback(async (ticketId: string) => { dispatch({ type: "started", operation: `detail:${ticketId}` }); try { const result = await api.getSupportTicket(ticketId); setDetail(result.detail); setAssignedAgentId(result.detail.ticket.assignedAgentId || ""); dispatch({ type: "succeeded" }); } catch (error) { dispatch({ type: "failed", message: supportFailure(error, "工单详情") }); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function mutate(label: string, action: (ticketId: string, version: number) => Promise<SupportTicketMutationResponse>) { if (!detail) return; const id = detail.ticket.ticketId; dispatch({ type: "started", operation: label }); try { await action(id, detail.ticket.version); const [list, selected] = await Promise.all([api.listSupportTickets(filters), api.getSupportTicket(id)]); setTickets(list.tickets); setNextCursor(list.nextCursor); setDetail(selected.detail); dispatch({ type: "succeeded", message: `${label}已完成` }); } catch (error) { dispatch({ type: "failed", message: supportFailure(error, label) }); } }
  async function claim(ticket: SupportTicket) { dispatch({ type: "started", operation: `claim:${ticket.ticketId}` }); try { await api.claimSupportTicket(ticket.ticketId, { expectedVersion: ticket.version, idempotencyKey: requestKey("claim") } satisfies ClaimSupportTicketRequest); const result = await api.listSupportTickets(filters); setTickets(result.tickets); setNextCursor(result.nextCursor); if (detail?.ticket.ticketId === ticket.ticketId) setDetail((await api.getSupportTicket(ticket.ticketId)).detail); dispatch({ type: "succeeded", message: "工单领取已完成" }); } catch (error) { dispatch({ type: "failed", message: supportFailure(error, "领取工单") }); } }
  const busy = ui.busy !== null;
  async function loadConversations() { try { setConversations((await api.listSupportConversations({ view: "all", limit: 100 })).conversations); } catch (error) { dispatch({ type: "failed", message: supportFailure(error, "实时会话队列") }); } }
  async function openConversation(id: string) { try { setConversationDetail(await api.getSupportConversation(id)); } catch (error) { dispatch({ type: "failed", message: supportFailure(error, "会话详情") }); } }
  async function refreshConversation(id: string) { setConversationDetail(await api.getSupportConversation(id)); await loadConversations(); }
  async function sendConversationMessage() { if (!conversationDetail || !conversationText.trim()) return; const key = requestKey("agent-chat"); try { await api.sendSupportMessage(conversationDetail.conversation.conversationId, { clientMessageId: key, messageType: "text", textContent: conversationText.trim(), idempotencyKey: key }); setConversationText(""); await refreshConversation(conversationDetail.conversation.conversationId); } catch (error) { dispatch({ type: "failed", message: supportFailure(error, "发送会话消息") }); } }
  async function mutateConversation(action: "accept" | "transfer" | "close") { if (!conversationDetail) return; const item = conversationDetail.conversation; const key = requestKey(`conversation-${action}`); try { if (action === "accept") await api.acceptSupportConversation(item.conversationId, { expectedVersion: item.version, idempotencyKey: key }); else if (action === "transfer") await api.transferSupportConversation(item.conversationId, { assignedAgentId: transferAgentId.trim(), expectedVersion: item.version, idempotencyKey: key }); else await api.closeSupportConversation(item.conversationId, { expectedVersion: item.version, idempotencyKey: key }); await refreshConversation(item.conversationId); } catch (error) { dispatch({ type: "failed", message: supportFailure(error, action === "accept" ? "接入会话" : action === "transfer" ? "转接会话" : "关闭会话") }); } }
  async function runBot(){if(!conversationDetail)return;const trigger=[...conversationDetail.messages].reverse().find(m=>m.senderType==="customer"||m.senderType==="worker");if(!trigger)return;try{const result=await api.runSupportBot(conversationDetail.conversation.conversationId,trigger.messageId);setBotRun(result.run);await refreshConversation(conversationDetail.conversation.conversationId);}catch(error){dispatch({type:"failed",message:supportFailure(error,"本地客服规则")});}}
  const isListingTickets = ui.busy === "list";

  return <div className="operations-workbench mobile-ops">
    <header className="mobile-ops__topbar"><div><span className="mobile-ops__eyebrow">客服运营</span><h1>工单与会话</h1><p>按服务时限排序，打开任务后在详情底部完成处理。</p></div><StatusTag tone={online ? "success" : "danger"}>{online ? "在线" : "离线"}</StatusTag></header>
    <p className="mobile-ops__oa-note"><strong>办公自动化系统承接边界：</strong>路由策略与知识库的批量维护后续由办公自动化系统承担；当前手机端保留即时领取、回复、转接、升级、解决和关闭工单。</p>
    <Card title="客服路由与服务时限"><Button onClick={() => setShowConfiguration(value => !value)}>{showConfiguration ? "收起路由配置" : "打开路由配置"}</Button></Card>
    <Card title="本地客服规则与知识库"><Button onClick={()=>setShowKnowledgeBase(v=>!v)}>{showKnowledgeBase?"收起知识库":"打开知识库"}</Button></Card>
    {showKnowledgeBase&&<SupportKnowledgeBasePage cityCode={cityCode}/>}
    {showConfiguration && <SupportRoutingConfigPage cityCode={cityCode} />}
    <Card title="客服工作台" actions={<><ScopeBadge scope={`城市：${cityLabel(cityCode)}`} /><StatusTag tone={online ? "success" : "danger"}>{online ? "服务已连接" : "当前离线"}</StatusTag></>}><div className="operations-form-grid">
      <FormField label="城市"><Select value={cityCode} onChange={event => setCityCode(event.target.value)}><option value="hangzhou">杭州</option><option value="shanghai">上海</option><option value="beijing">北京</option></Select></FormField>
      <FormField label="队列"><Select value={workbenchView} onChange={event => setWorkbenchView(event.target.value as SupportTicketWorkbenchView)}><option value="mine">分配给我</option><option value="skill_group">技能组待领取</option><option value="all">城市全量</option></Select></FormField>
      <FormField label="状态"><Select value={status} onChange={event => setStatus(event.target.value as SupportTicketStatus | "")}><option value="">全部</option><option value="open">待处理</option><option value="processing">处理中</option><option value="waiting_requester">等待诉求人</option><option value="escalated">已升级</option><option value="resolved">已解决</option><option value="closed">已关闭</option></Select></FormField>
      <FormField label="优先级"><Select value={priority} onChange={event => setPriority(event.target.value as SupportTicketPriority | "")}><option value="">全部</option><option value="low">低</option><option value="normal">普通</option><option value="high">高</option><option value="urgent">紧急</option><option value="critical">严重</option></Select></FormField>
      <FormField label="来源"><Select value={source} onChange={event => setSource(event.target.value as SupportTicketSource | "")}><option value="">全部</option><option value="customer">客户</option><option value="worker">师傅</option><option value="enterprise">企业客户</option><option value="admin">后台人员</option></Select></FormField>
      <FormField label="问题类型"><Select value={type} onChange={event => setType(event.target.value as SupportTicketType | "")}><option value="">全部</option><option value="order_question">订单咨询</option><option value="order_dispute">订单争议</option><option value="service_complaint">服务投诉</option><option value="withdrawal_issue">提现问题</option><option value="account_issue">账号问题</option><option value="safety">安全事件</option><option value="other">其他</option></Select></FormField>
    </div><div className="operations-inline-actions" style={{ marginTop: 10 }}><Button variant="primary" disabled={busy} onClick={() => void load()}>刷新队列</Button></div></Card>
    {!online && <div className="operations-alert operations-alert--offline" role="status">网络已断开，旧队列仅供核对，领取、转接、回复和状态变更已停用。</div>}
    {ui.error && <ApiErrorPanel title="客服操作失败" detail={ui.error} action={<Button onClick={() => void load()}>刷新最新数据</Button>} />}{ui.notice && <div className="operations-alert" role="status">{ui.notice}</div>}
    <Card title="实时会话队列" actions={<Button disabled={!online} onClick={() => void loadConversations()}>刷新会话</Button>}>{conversations.length === 0 ? <EmptyState title="尚未载入实时会话" /> : <Table rows={conversations} getRowKey={row => row.conversationId} columns={[{ key: "requester", title: "诉求人", render: row => `${businessLabel(row.source)} / ${row.requesterId}` }, { key: "status", title: "状态", render: row => <StatusTag tone={statusTone(row.status)}>{statusLabel(row.status)}</StatusTag> }, { key: "open", title: "详情", render: row => <Button onClick={() => void openConversation(row.conversationId)}>打开</Button> }]} />}{conversationDetail && <div className="operations-section-stack" style={{ marginTop: 12 }}>{conversationDetail.messages.map(message => <div key={message.messageId}><strong>{businessLabel(message.senderType)}</strong>：{message.textContent || "图片消息"}</div>)}<Button disabled={!online || conversationDetail.conversation.status!=="queueing"} onClick={()=>void runBot()}>运行本地确定性客服规则</Button>{botRun&&<div className="operations-alert"><StatusTag tone={botRun.decision==="reply"?"success":"warning"}>{statusLabel(botRun.decision)}</StatusTag> 规则提供方：{businessLabel(botRun.provider)}；提供方状态：{statusLabel(botRun.providerStatus)}；{botRun.externalProviderExecuted ? "已执行外部服务" : "未执行外部服务"}；原因代码：{botRun.reasonCodes.join("、") || "无"}</div>}<Textarea aria-label="会话回复" value={conversationText} onChange={event => setConversationText(event.target.value)} /><Button variant="primary" disabled={!online || !conversationText.trim() || conversationDetail.conversation.status === "closed"} onClick={() => void sendConversationMessage()}>通过备用接口发送</Button><div className="operations-inline-actions"><Button disabled={!online || (conversationDetail.conversation.status !== "queueing" && conversationDetail.conversation.status !== "transferred")} onClick={() => void mutateConversation("accept")}>接入</Button><Input aria-label="转接客服编号" value={transferAgentId} onChange={event => setTransferAgentId(event.target.value)} placeholder="客服人员编号" /><Button disabled={!online || !transferAgentId.trim() || conversationDetail.conversation.status === "closed"} onClick={() => void mutateConversation("transfer")}>转接</Button><Button disabled={!online || conversationDetail.conversation.status === "closed"} onClick={() => void mutateConversation("close")}>关闭</Button></div></div>}</Card>
    <Card title={businessLabel(workbenchView)} actions={<StatusTag tone="muted">{tickets.length} 条</StatusTag>}>{isListingTickets && tickets.length === 0 ? <LoadingState title="正在读取客服队列" /> : tickets.length === 0 ? <EmptyState title="没有符合筛选条件的工单" /> : <Table rows={tickets} getRowKey={row => row.ticketId} columns={[
      { key: "subject", title: "主题", render: row => row.subject }, { key: "status", title: "状态", render: row => <StatusTag tone={tone(row.status)}>{statusLabel(row.status)}</StatusTag> }, { key: "sla", title: "剩余处理时限", render: row => { const state = slaState(row); return <StatusTag tone={state.tone}>{state.label}</StatusTag>; } }, { key: "priority", title: "优先级", render: row => businessLabel(row.priority) }, { key: "source", title: "来源", render: row => businessLabel(row.source) }, { key: "type", title: "类型", render: row => businessLabel(row.type) }, { key: "agent", title: "负责客服", render: row => row.assignedAgentId || "未分配" }, { key: "group", title: "技能组", render: row => row.assignedSkillGroupId || "—" }, { key: "claim", title: "领取", render: row => workbenchView === "skill_group" && !row.assignedAgentId ? <Button variant="primary" disabled={busy || !online} onClick={() => void claim(row)}>领取</Button> : null }, { key: "open", title: "详情", render: row => <Button disabled={busy} onClick={() => void open(row.ticketId)}>打开</Button> }
    ]} />}{nextCursor && <div style={{ marginTop: 10 }}><Button disabled={busy} onClick={() => void loadMore()}>加载更多</Button></div>}</Card>
    {detail && <Card title={`工单 · ${detail.ticket.subject}`} actions={<StatusTag tone={tone(detail.ticket.status)}>{statusLabel(detail.ticket.status)}</StatusTag>}><div className="operations-section-stack">
      <p style={{ margin: 0 }}>{detail.ticket.description}</p><small>诉求人：{businessLabel(detail.ticket.source)} / {detail.ticket.requesterId} · 类型：{businessLabel(detail.ticket.type)} · 优先级：{businessLabel(detail.ticket.priority)} · 数据版本：{detail.ticket.version}</small>
      {detail.ticket.linkedAftersaleComplaintId && <Card title="关联售后投诉"><p style={{ margin: 0 }}><strong>{detail.ticket.linkedAftersaleComplaintId}</strong> · 此处仅提供只读联动；解决、定责、返工和补偿仍在售后工作台处理。</p></Card>}
      <div className="operations-form-grid"><FormField label="负责客服编号"><Input value={assignedAgentId} onChange={event => setAssignedAgentId(event.target.value)} /></FormField><Button disabled={!online || busy || !assignedAgentId.trim() || detail.ticket.status === "closed"} onClick={() => void mutate("分配工单", (id, version) => api.assignSupportTicket(id, { assignedAgentId: assignedAgentId.trim(), expectedVersion: version, idempotencyKey: requestKey("assign") } satisfies AssignSupportTicketRequest))}>分配</Button></div>
      <FormField label="工单备注"><Textarea value={comment} onChange={event => setComment(event.target.value)} /></FormField><FormField label="可见范围"><Select value={commentVisibility} onChange={event => setCommentVisibility(event.target.value as AdminAddSupportTicketCommentRequest["visibility"])}><option value="all">诉求人可见</option><option value="internal">仅内部可见</option></Select></FormField><Button variant="primary" disabled={!online || busy || !comment.trim() || detail.ticket.status === "closed"} onClick={() => void mutate("添加备注", id => api.addSupportTicketComment(id, { content: comment.trim(), visibility: commentVisibility, idempotencyKey: requestKey("comment") }).then(result => { setComment(""); return result; }))}>添加备注</Button>
      <FormField label="升级或关闭原因"><Textarea value={reason} onChange={event => setReason(event.target.value)} /></FormField><div className="operations-inline-actions"><Button disabled={!online || busy || !reason.trim() || detail.ticket.status === "closed"} onClick={() => void mutate("升级工单", (id, version) => api.escalateSupportTicket(id, { reason: reason.trim(), expectedVersion: version, idempotencyKey: requestKey("escalate") } satisfies EscalateSupportTicketRequest))}>升级</Button><Button disabled={!online || busy || detail.ticket.status !== "resolved"} onClick={() => void mutate("关闭工单", (id, version) => api.closeSupportTicket(id, { reason: reason.trim() || undefined, expectedVersion: version, idempotencyKey: requestKey("close") } satisfies CloseSupportTicketRequest))}>关闭</Button></div>
      <FormField label="解决代码"><Input value={resolutionCode} onChange={event => setResolutionCode(event.target.value)} placeholder="填写服务端认可的解决代码" /></FormField><FormField label="解决说明"><Textarea value={resolutionNote} onChange={event => setResolutionNote(event.target.value)} /></FormField><Button variant="primary" disabled={!online || busy || !resolutionCode.trim() || detail.ticket.status === "resolved" || detail.ticket.status === "closed"} onClick={() => void mutate("解决工单", (id, version) => api.resolveSupportTicket(id, { resolutionCode: resolutionCode.trim(), resolutionNote: resolutionNote.trim() || undefined, expectedVersion: version, idempotencyKey: requestKey("resolve") } satisfies ResolveSupportTicketRequest))}>记录解决结果</Button>
      <Card title="工单时间线">{detail.events.length === 0 ? <EmptyState title="暂无工单事件" /> : detail.events.map(event => <div key={event.ticketEventId} style={{ borderBottom: "1px solid #e5e7eb", padding: "8px 0" }}><strong>{statusLabel(event.eventType)}</strong> · {businessLabel(event.actorType)}<p style={{ margin: "3px 0" }}>{event.content || "状态发生变化"}</p><small>{businessLabel(event.visibility)} · {formatDateTime(event.createdAt)}</small></div>)}</Card>
    </div></Card>}
  </div>;
}
