import { useState } from "react";
import type { SupportKbMutationResponse } from "@xlb/types";
import { ApiErrorPanel, Button, Card, FormField, Input, StatusTag, Textarea } from "@xlb/ui";
import { adminOpsApi as api } from "../adminAuth";
const key=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
export function SupportKnowledgeBasePage({cityCode}:{cityCode:string}){
 const [article,setArticle]=useState<SupportKbMutationResponse|null>(null),[slug,setSlug]=useState(""),[language,setLanguage]=useState("zh-cn"),[title,setTitle]=useState(""),[body,setBody]=useState(""),[keywords,setKeywords]=useState(""),[intents,setIntents]=useState(""),[note,setNote]=useState(""),[error,setError]=useState<string|null>(null);
 const terms=(v:string)=>v.split(",").map(x=>x.trim()).filter(Boolean);
 async function act(action:"create"|"revision"|"submit"|"approve"|"reject"|"publish") { try { setError(null); let result:SupportKbMutationResponse;if(action==="create") result=await api.createSupportKbArticle({slug,language,title,bodyMarkdown:body,keywords:terms(keywords),intentTags:terms(intents),idempotencyKey:key("kb-create")}); else {if(!article) return;const a=article.article,v=article.version;if(action==="revision")result=await api.createSupportKbRevision(a.articleId,{expectedVersion:a.version,title,bodyMarkdown:body,keywords:terms(keywords),intentTags:terms(intents),idempotencyKey:key("kb-revision")});else if(action==="submit")result=await api.submitSupportKbRevision(a.articleId,v.articleVersionId,{note:note||undefined,idempotencyKey:key("kb-submit")});else if(action==="approve")result=await api.approveSupportKbRevision(a.articleId,v.articleVersionId,{note:note||undefined,idempotencyKey:key("kb-approve")});else if(action==="reject")result=await api.rejectSupportKbRevision(a.articleId,v.articleVersionId,{note:note||undefined,idempotencyKey:key("kb-reject")});else result=await api.publishSupportKbRevision(a.articleId,{versionId:v.articleVersionId,expectedVersion:a.version,idempotencyKey:key("kb-publish")});}setArticle(result);}catch(e){setError(e instanceof Error?e.message:"Knowledge operation failed");}}
 return <Card title="Support Knowledge Base" actions={<><StatusTag tone="primary">city: {cityCode}</StatusTag>{article&&<><StatusTag tone="primary">{article.article.lifecycleStatus}</StatusTag><StatusTag tone="warning">{article.version.reviewStatus}</StatusTag></>}</>}><div style={{display:"grid",gap:8}}>{error&&<ApiErrorPanel title="Knowledge operation failed" detail={error}/>}<FormField label="Slug"><Input value={slug} onChange={e=>setSlug(e.target.value)}/></FormField><FormField label="Language"><Input value={language} onChange={e=>setLanguage(e.target.value)}/></FormField><FormField label="Title"><Input value={title} onChange={e=>setTitle(e.target.value)}/></FormField><FormField label="Approved information-only Markdown"><Textarea value={body} onChange={e=>setBody(e.target.value)}/></FormField><FormField label="Keywords (comma separated)"><Input value={keywords} onChange={e=>setKeywords(e.target.value)}/></FormField><FormField label="Intent tags"><Input value={intents} onChange={e=>setIntents(e.target.value)}/></FormField><FormField label="Review note"><Textarea value={note} onChange={e=>setNote(e.target.value)}/></FormField><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Button variant="primary" onClick={()=>void act("create")}>Create article</Button><Button disabled={!article} onClick={()=>void act("revision")}>New immutable revision</Button><Button disabled={!article||article.version.reviewStatus!=="draft"} onClick={()=>void act("submit")}>Submit review</Button><Button disabled={!article||article.version.reviewStatus!=="pending_review"} onClick={()=>void act("approve")}>Approve</Button><Button disabled={!article||article.version.reviewStatus!=="pending_review"} onClick={()=>void act("reject")}>Reject</Button><Button disabled={!article||article.version.reviewStatus!=="approved"} onClick={()=>void act("publish")}>Publish</Button></div>{article&&<small>Article {article.article.articleId} · immutable revision {article.version.revision} · SHA-256 {article.version.contentSha256}</small>}</div></Card>;
}
