import { useCallback, useEffect, useMemo, useReducer, useState } from "react";
import type { AdminAddSupportTicketCommentRequest, AssignSupportTicketRequest, ClaimSupportTicketRequest, CloseSupportTicketRequest, EscalateSupportTicketRequest, ResolveSupportTicketRequest, SupportBotRun, SupportConversation, SupportConversationDetailResponse, SupportTicket, SupportTicketDetailResponse, SupportTicketListFilters, SupportTicketListResponse, SupportTicketMutationResponse, SupportTicketPriority, SupportTicketSource, SupportTicketStatus, SupportTicketType, SupportTicketWorkbenchView } from "@xlb/types";
import { ApiErrorPanel, Button, Card, EmptyState, FormField, Input, LoadingState, ScopeBadge, Select, StatusTag, Table, Textarea } from "@xlb/ui";
import { adminOpsApi as api } from "../adminAuth";
import { initialAdminSupportUiState, adminSupportUiReducer } from "../features/support/reducer";
import { SupportRoutingConfigPage } from "./SupportRoutingConfigPage";
import { SupportKnowledgeBasePage } from "./SupportKnowledgeBasePage";

const requestKey = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const tone = (status: SupportTicketStatus) => status === "resolved" || status === "closed" ? "success" : status === "escalated" ? "danger" : status === "processing" ? "primary" : "warning";
const nearDueWindowMs = 30 * 60 * 1000;

function effectiveSlaDueAt(ticket: SupportTicket): string | null {
  return ticket.firstRespondedAt
    ? ticket.slaResolutionDueAt
    : ticket.slaFirstResponseDueAt || ticket.slaResolutionDueAt;
}

function slaState(ticket: SupportTicket, now = Date.now()): { label: string; tone: "success" | "warning" | "danger" | "muted" } {
  const dueAt = effectiveSlaDueAt(ticket);
  if (!dueAt) return { label: "No SLA", tone: "muted" };
  const remaining = new Date(dueAt).getTime() - now;
  if (remaining <= 0) return { label: `Overdue ${Math.ceil(Math.abs(remaining) / 60000)}m`, tone: "danger" };
  if (remaining <= nearDueWindowMs) return { label: `Due in ${Math.ceil(remaining / 60000)}m`, tone: "warning" };
  return { label: `Due in ${Math.ceil(remaining / 60000)}m`, tone: "success" };
}

export function SupportTicketsPage({ initialCityCode }: { initialCityCode?: string }) {
  const [ui, dispatch] = useReducer(adminSupportUiReducer, initialAdminSupportUiState);
  const [cityCode, setCityCode] = useState(initialCityCode || "hangzhou");
  const [tickets, setTickets] = useState<SupportTicketListResponse["tickets"]>([]);
  const [nextCursor, setNextCursor] = useState<string | null>(null);
  const [detail, setDetail] = useState<SupportTicketDetailResponse["detail"] | null>(null);
  const [status, setStatus] = useState<SupportTicketStatus | "">(""); const [priority, setPriority] = useState<SupportTicketPriority | "">("");
  const [source, setSource] = useState<SupportTicketSource | "">(""); const [type, setType] = useState<SupportTicketType | "">("");
  const [assignedAgentId, setAssignedAgentId] = useState(""); const [comment, setComment] = useState("");
  const [commentVisibility, setCommentVisibility] = useState<AdminAddSupportTicketCommentRequest["visibility"]>("all");
  const [reason, setReason] = useState(""); const [resolutionCode, setResolutionCode] = useState("answered"); const [resolutionNote, setResolutionNote] = useState("");
  const [showConfiguration, setShowConfiguration] = useState(false);
  const [showKnowledgeBase,setShowKnowledgeBase]=useState(false);
  const [workbenchView, setWorkbenchView] = useState<SupportTicketWorkbenchView>("mine");
  const [conversations, setConversations] = useState<SupportConversation[]>([]); const [conversationDetail, setConversationDetail] = useState<SupportConversationDetailResponse | null>(null); const [conversationText, setConversationText] = useState(""); const [transferAgentId, setTransferAgentId] = useState("");
  const [botRun,setBotRun]=useState<SupportBotRun|null>(null);
  const filters = useMemo<SupportTicketListFilters>(() => ({ status: status || undefined, priority: priority || undefined, source: source || undefined, type: type || undefined, view: workbenchView, sort: "sla_due", limit: 100 }), [priority, source, status, type, workbenchView]);
  const load = useCallback(async () => { dispatch({ type: "started", operation: "list" }); try { window.history.replaceState({}, "", `#/support?cityCode=${encodeURIComponent(cityCode)}`); const result = await api.listSupportTickets(filters); setTickets(result.tickets); setNextCursor(result.nextCursor); dispatch({ type: "succeeded" }); } catch (error) { dispatch({ type: "failed", message: error instanceof Error ? error.message : "Unable to load support queue" }); } }, [cityCode, filters]);
  const loadMore = useCallback(async () => { if (!nextCursor) return; dispatch({ type: "started", operation: "list-more" }); try { const result = await api.listSupportTickets({ ...filters, cursor: nextCursor }); setTickets(current => [...current, ...result.tickets]); setNextCursor(result.nextCursor); dispatch({ type: "succeeded" }); } catch (error) { dispatch({ type: "failed", message: error instanceof Error ? error.message : "Unable to load more support tickets" }); } }, [filters, nextCursor]);
  const open = useCallback(async (ticketId: string) => { dispatch({ type: "started", operation: `detail:${ticketId}` }); try { const result = await api.getSupportTicket(ticketId); setDetail(result.detail); setAssignedAgentId(result.detail.ticket.assignedAgentId || ""); dispatch({ type: "succeeded" }); } catch (error) { dispatch({ type: "failed", message: error instanceof Error ? error.message : "Unable to load ticket detail" }); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function mutate(label: string, action: (ticketId: string, version: number) => Promise<SupportTicketMutationResponse>) { if (!detail) return; const id = detail.ticket.ticketId; dispatch({ type: "started", operation: label }); try { await action(id, detail.ticket.version); const [list, selected] = await Promise.all([api.listSupportTickets(filters), api.getSupportTicket(id)]); setTickets(list.tickets); setNextCursor(list.nextCursor); setDetail(selected.detail); dispatch({ type: "succeeded", message: `${label} completed` }); } catch (error) { dispatch({ type: "failed", message: error instanceof Error ? error.message : `${label} failed` }); } }
  async function claim(ticket: SupportTicket) { dispatch({ type: "started", operation: `claim:${ticket.ticketId}` }); try { await api.claimSupportTicket(ticket.ticketId, { expectedVersion: ticket.version, idempotencyKey: requestKey("claim") } satisfies ClaimSupportTicketRequest); const result = await api.listSupportTickets(filters); setTickets(result.tickets); setNextCursor(result.nextCursor); if (detail?.ticket.ticketId === ticket.ticketId) setDetail((await api.getSupportTicket(ticket.ticketId)).detail); dispatch({ type: "succeeded", message: "claim completed" }); } catch (error) { dispatch({ type: "failed", message: error instanceof Error ? error.message : "claim failed" }); } }
  const busy = ui.busy !== null;
  async function loadConversations() { try { setConversations((await api.listSupportConversations({ view: "all", limit: 100 })).conversations); } catch (error) { dispatch({ type: "failed", message: error instanceof Error ? error.message : "Unable to load conversations" }); } }
  async function openConversation(id: string) { try { setConversationDetail(await api.getSupportConversation(id)); } catch (error) { dispatch({ type: "failed", message: error instanceof Error ? error.message : "Unable to open conversation" }); } }
  async function refreshConversation(id: string) { setConversationDetail(await api.getSupportConversation(id)); await loadConversations(); }
  async function sendConversationMessage() { if (!conversationDetail || !conversationText.trim()) return; const key = requestKey("agent-chat"); try { await api.sendSupportMessage(conversationDetail.conversation.conversationId, { clientMessageId: key, messageType: "text", textContent: conversationText.trim(), idempotencyKey: key }); setConversationText(""); await refreshConversation(conversationDetail.conversation.conversationId); } catch (error) { dispatch({ type: "failed", message: error instanceof Error ? error.message : "REST message failed" }); } }
  async function mutateConversation(action: "accept" | "transfer" | "close") { if (!conversationDetail) return; const item = conversationDetail.conversation; const key = requestKey(`conversation-${action}`); try { if (action === "accept") await api.acceptSupportConversation(item.conversationId, { expectedVersion: item.version, idempotencyKey: key }); else if (action === "transfer") await api.transferSupportConversation(item.conversationId, { assignedAgentId: transferAgentId.trim(), expectedVersion: item.version, idempotencyKey: key }); else await api.closeSupportConversation(item.conversationId, { expectedVersion: item.version, idempotencyKey: key }); await refreshConversation(item.conversationId); } catch (error) { dispatch({ type: "failed", message: error instanceof Error ? error.message : `Unable to ${action} conversation` }); } }
  async function runBot(){if(!conversationDetail)return;const trigger=[...conversationDetail.messages].reverse().find(m=>m.senderType==="customer"||m.senderType==="worker");if(!trigger)return;try{const result=await api.runSupportBot(conversationDetail.conversation.conversationId,trigger.messageId);setBotRun(result.run);await refreshConversation(conversationDetail.conversation.conversationId);}catch(error){dispatch({type:"failed",message:error instanceof Error?error.message:"Bot orchestration failed"});}}
  return <div style={{ display: "grid", gap: 16 }}>
    <Card title="Support routing and SLA"><Button onClick={() => setShowConfiguration(value => !value)}>{showConfiguration ? "Close routing configuration" : "Open routing configuration"}</Button></Card>
    <Card title="Bot and knowledge base"><Button onClick={()=>setShowKnowledgeBase(v=>!v)}>{showKnowledgeBase?"Close knowledge base":"Open knowledge base"}</Button></Card>
    {showKnowledgeBase&&<SupportKnowledgeBasePage cityCode={cityCode}/>}
    {showConfiguration && <SupportRoutingConfigPage cityCode={cityCode} />}
    <Card title="Agent Workbench" actions={<ScopeBadge scope={`city: ${cityCode}`} />}><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(170px,1fr))", gap: 10 }}>
      <FormField label="City"><Input value={cityCode} onChange={event => setCityCode(event.target.value)} /></FormField>
      <FormField label="Queue"><Select value={workbenchView} onChange={event => setWorkbenchView(event.target.value as SupportTicketWorkbenchView)}><option value="mine">Assigned to me</option><option value="skill_group">Skill-group pool</option><option value="all">City supervision</option></Select></FormField>
      <FormField label="Status"><Select value={status} onChange={event => setStatus(event.target.value as SupportTicketStatus | "")}><option value="">All</option><option value="open">Open</option><option value="processing">Processing</option><option value="waiting_requester">Waiting requester</option><option value="escalated">Escalated</option><option value="resolved">Resolved</option><option value="closed">Closed</option></Select></FormField>
      <FormField label="Priority"><Select value={priority} onChange={event => setPriority(event.target.value as SupportTicketPriority | "")}><option value="">All</option><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option><option value="critical">Critical</option></Select></FormField>
      <FormField label="Source"><Select value={source} onChange={event => setSource(event.target.value as SupportTicketSource | "")}><option value="">All</option><option value="customer">Customer</option><option value="worker">Worker</option><option value="enterprise">Enterprise</option><option value="admin">Admin</option></Select></FormField>
      <FormField label="Type"><Select value={type} onChange={event => setType(event.target.value as SupportTicketType | "")}><option value="">All</option><option value="order_question">Order question</option><option value="order_dispute">Order dispute</option><option value="service_complaint">Service complaint</option><option value="withdrawal_issue">Withdrawal issue</option><option value="account_issue">Account issue</option><option value="safety">Safety</option><option value="other">Other</option></Select></FormField>
    </div><div style={{ marginTop: 10 }}><Button variant="primary" disabled={busy} onClick={() => void load()}>Refresh queue</Button></div></Card>
    {ui.error && <ApiErrorPanel title="Support operation failed" detail={ui.error} />}{ui.notice && <Card title="Updated"><p style={{ margin: 0 }}>{ui.notice}</p></Card>}
    <Card title="Realtime conversation queue" actions={<Button onClick={() => void loadConversations()}>Refresh conversations</Button>}>{conversations.length === 0 ? <EmptyState title="No conversations loaded" /> : <Table rows={conversations} getRowKey={row => row.conversationId} columns={[{ key: "requester", title: "Requester", render: row => `${row.source} / ${row.requesterId}` }, { key: "status", title: "Status", render: row => <StatusTag tone={row.status === "closed" ? "muted" : row.status === "active" ? "success" : "warning"}>{row.status}</StatusTag> }, { key: "open", title: "", render: row => <Button onClick={() => void openConversation(row.conversationId)}>Open</Button> }]} />}{conversationDetail && <div style={{ display: "grid", gap: 8, marginTop: 12 }}>{conversationDetail.messages.map(message => <div key={message.messageId}><strong>{message.senderType}</strong>: {message.textContent || "Image"}</div>)}<Button disabled={conversationDetail.conversation.status!=="queueing"} onClick={()=>void runBot()}>Run deterministic local Bot</Button>{botRun&&<div><StatusTag tone={botRun.decision==="reply"?"success":"warning"}>{botRun.decision}</StatusTag> Provider: {botRun.provider}/{botRun.providerStatus} · external executed: {String(botRun.externalProviderExecuted)} · reasons: {botRun.reasonCodes.join(", ")}</div>}<Textarea value={conversationText} onChange={event => setConversationText(event.target.value)} /><Button variant="primary" disabled={!conversationText.trim() || conversationDetail.conversation.status === "closed"} onClick={() => void sendConversationMessage()}>Send via REST fallback</Button><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><Button disabled={conversationDetail.conversation.status !== "queueing" && conversationDetail.conversation.status !== "transferred"} onClick={() => void mutateConversation("accept")}>Accept</Button><Input value={transferAgentId} onChange={event => setTransferAgentId(event.target.value)} placeholder="Agent ID" /><Button disabled={!transferAgentId.trim() || conversationDetail.conversation.status === "closed"} onClick={() => void mutateConversation("transfer")}>Transfer</Button><Button disabled={conversationDetail.conversation.status === "closed"} onClick={() => void mutateConversation("close")}>Close</Button></div></div>}</Card>
    <Card title={workbenchView === "mine" ? "Assigned to me" : workbenchView === "skill_group" ? "Skill-group pool" : "City support tickets"} actions={<StatusTag tone="muted">{tickets.length}</StatusTag>}>{ui.busy === "list" && tickets.length === 0 ? <LoadingState title="Loading support queue" /> : tickets.length === 0 ? <EmptyState title="No tickets match the filters" /> : <Table rows={tickets} getRowKey={row => row.ticketId} columns={[
      { key: "subject", title: "Subject", render: row => row.subject }, { key: "status", title: "Status", render: row => <StatusTag tone={tone(row.status)}>{row.status}</StatusTag> }, { key: "sla", title: "SLA remaining", render: row => { const state = slaState(row); return <StatusTag tone={state.tone}>{state.label}</StatusTag>; } }, { key: "priority", title: "Priority", render: row => row.priority }, { key: "source", title: "Source", render: row => row.source }, { key: "type", title: "Type", render: row => row.type }, { key: "agent", title: "Assigned agent", render: row => row.assignedAgentId || "Unassigned" }, { key: "group", title: "Skill group", render: row => row.assignedSkillGroupId || "-" }, { key: "claim", title: "", render: row => workbenchView === "skill_group" && !row.assignedAgentId ? <Button variant="primary" disabled={busy} onClick={() => void claim(row)}>Claim</Button> : null }, { key: "open", title: "", render: row => <Button disabled={busy} onClick={() => void open(row.ticketId)}>Open</Button> }
    ]} />}{nextCursor && <div style={{ marginTop: 10 }}><Button disabled={busy} onClick={() => void loadMore()}>Load more</Button></div>}</Card>
    {detail && <Card title={`Ticket · ${detail.ticket.subject}`} actions={<StatusTag tone={tone(detail.ticket.status)}>{detail.ticket.status}</StatusTag>}><div style={{ display: "grid", gap: 12 }}>
      <p style={{ margin: 0 }}>{detail.ticket.description}</p><small>Requester: {detail.ticket.source} / {detail.ticket.requesterId} · Type: {detail.ticket.type} · Priority: {detail.ticket.priority} · Version: {detail.ticket.version}</small>
      {detail.ticket.linkedAftersaleComplaintId && <Card title="Linked aftersale complaint"><p style={{ margin: 0 }}><strong>{detail.ticket.linkedAftersaleComplaintId}</strong> · Read-only link. Complaint resolution, liability, repair and compensation remain in Aftersale Operations.</p></Card>}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(240px,1fr))", gap: 10 }}><FormField label="Assigned agent ID"><Input value={assignedAgentId} onChange={event => setAssignedAgentId(event.target.value)} /></FormField><Button disabled={busy || !assignedAgentId.trim() || detail.ticket.status === "closed"} onClick={() => void mutate("assign", (id, version) => api.assignSupportTicket(id, { assignedAgentId: assignedAgentId.trim(), expectedVersion: version, idempotencyKey: requestKey("assign") } satisfies AssignSupportTicketRequest))}>Assign</Button></div>
      <FormField label="Comment"><Textarea value={comment} onChange={event => setComment(event.target.value)} /></FormField><FormField label="Visibility"><Select value={commentVisibility} onChange={event => setCommentVisibility(event.target.value as AdminAddSupportTicketCommentRequest["visibility"])}><option value="all">Requester visible</option><option value="internal">Internal only</option></Select></FormField><Button variant="primary" disabled={busy || !comment.trim() || detail.ticket.status === "closed"} onClick={() => void mutate("comment", id => api.addSupportTicketComment(id, { content: comment.trim(), visibility: commentVisibility, idempotencyKey: requestKey("comment") }).then(result => { setComment(""); return result; }))}>Add comment</Button>
      <FormField label="Escalation / close reason"><Textarea value={reason} onChange={event => setReason(event.target.value)} /></FormField><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><Button disabled={busy || !reason.trim() || detail.ticket.status === "closed"} onClick={() => void mutate("escalate", (id, version) => api.escalateSupportTicket(id, { reason: reason.trim(), expectedVersion: version, idempotencyKey: requestKey("escalate") } satisfies EscalateSupportTicketRequest))}>Escalate</Button><Button disabled={busy || detail.ticket.status !== "resolved"} onClick={() => void mutate("close", (id, version) => api.closeSupportTicket(id, { reason: reason.trim() || undefined, expectedVersion: version, idempotencyKey: requestKey("close") } satisfies CloseSupportTicketRequest))}>Close</Button></div>
      <FormField label="Resolution code"><Input value={resolutionCode} onChange={event => setResolutionCode(event.target.value)} /></FormField><FormField label="Resolution note"><Textarea value={resolutionNote} onChange={event => setResolutionNote(event.target.value)} /></FormField><Button variant="primary" disabled={busy || !resolutionCode.trim() || detail.ticket.status === "resolved" || detail.ticket.status === "closed"} onClick={() => void mutate("resolve", (id, version) => api.resolveSupportTicket(id, { resolutionCode: resolutionCode.trim(), resolutionNote: resolutionNote.trim() || undefined, expectedVersion: version, idempotencyKey: requestKey("resolve") } satisfies ResolveSupportTicketRequest))}>Resolve</Button>
      <Card title="Timeline">{detail.events.length === 0 ? <EmptyState title="No events" /> : detail.events.map(event => <div key={event.ticketEventId} style={{ borderBottom: "1px solid #e5e7eb", padding: "8px 0" }}><strong>{event.eventType}</strong> · {event.actorType}<p style={{ margin: "3px 0" }}>{event.content || "State transition"}</p><small>{event.visibility} · {event.createdAt}</small></div>)}</Card>
    </div></Card>}
  </div>;
}
