import type { MaterialRecipe } from "../tokenTypes.js";
import { defineMaterialRecipe } from "./defineMaterialRecipe.js";

/**
 * Customer material contract derived from the locked Customer Home visual truth.
 *
 * This recipe is intentionally declarative: it references canonical token
 * paths only and carries no route, workflow, price, permission, or campaign
 * semantics. Components consume these references in later Phase 25 gates.
 */
export const customerLiquidGlassMaterialRecipe = defineMaterialRecipe({
  id: "customer-liquid-glass",
  role: "customer",
  sourceAuthority: "docs/design/ui/references/customer-home-visual-truth.png",
  readiness: "ready",
  density: "comfortable",
  viewportToken: "breakpoint.compact",
  surfaceTokens: [
    "surface.page",
    "surface.glass",
    "surface.elevated",
    "role.customer.cream",
    "role.customer.ambient",
    "role.customer.glassTint",
    "glass.tint",
    "glass.saturation",
    "glass.backdropBlur",
    "glass.ambientShadow",
    "blur.md",
    "shadow.ambient",
  ],
  borderTokens: [
    "border.glassHighlight",
    "border.glassInner",
    "glass.edgeHighlight",
    "glass.innerStroke",
    "stroke.hairline",
    "stroke.regular",
    "radius.lg",
    "radius.xl",
    "radius.xxl",
    "radius.pill",
  ],
  typographyTokens: [
    "font.familySans",
    "font.size.sm",
    "font.size.md",
    "font.size.lg",
    "font.size.xl",
    "font.size.display",
    "font.weight.regular",
    "font.weight.medium",
    "font.weight.bold",
    "font.lineHeight.tight",
    "font.lineHeight.normal",
    "font.lineHeight.display",
    "font.numeric",
    "role.customer.ink",
    "role.customer.coffee",
  ],
  layoutTokens: [
    "grid.columnsCompact",
    "grid.gutterCompact",
    "spacing.sm",
    "spacing.md",
    "spacing.lg",
    "spacing.xl",
    "safeArea.top",
    "safeArea.right",
    "safeArea.bottom",
    "safeArea.left",
    "safeArea.bottomNavigation",
    "size.touchTarget",
    "size.controlMd",
    "size.controlLg",
    "size.bottomNavigation",
    "zIndex.sticky",
  ],
  protectedSemanticTokens: [
    "border.focus",
    "shadow.focus",
    "color.info",
    "color.success",
    "color.warning",
    "color.danger",
    "state.loading",
    "state.success",
    "state.warning",
    "state.error",
    "state.stale",
  ],
  supportedCapabilities: [
    "backdrop-filter",
    "forced-colors",
    "reduced-motion",
    "low-power",
  ],
  fallbackRecipeIds: [
    "no-backdrop-filter",
    "forced-colors",
    "reduced-motion",
    "low-power",
  ],
} as const satisfies MaterialRecipe);
