import type { MaterialRecipe, MaterialRecipeId } from "../tokenTypes.js";
import { defineMaterialRecipe } from "./defineMaterialRecipe.js";

type NonCustomerMaterialRecipeId = Exclude<MaterialRecipeId, "customer-liquid-glass">;

/**
 * Gate 1B role recipes may only point at the canonical token tree. They do not
 * contain CSS values, workflow state, business data, or page implementation.
 */
export interface RoleMaterialRecipe extends MaterialRecipe {
  /** Ordered token references for the role's highest-priority render concerns. */
  readonly priorityTokenRefs: readonly string[];
}

export const workerOperationalDarkRecipe = defineMaterialRecipe({
  id: "worker-operational-dark",
  role: "worker",
  sourceAuthority: "docs/design/figma/frames/worker/worker_grabhall_online_1-1515.png",
  readiness: "ready",
  density: "comfortable",
  viewportToken: "breakpoint.compact",
  surfaceTokens: [
    "role.worker.page",
    "role.worker.panel",
    "role.worker.text",
    "role.worker.muted",
    "surface.scrim",
  ],
  borderTokens: ["border.subtle", "border.strong", "border.focus"],
  typographyTokens: [
    "font.familySans",
    "font.familySerif",
    "font.familyMono",
    "font.numeric",
    "font.size.sm",
    "font.size.md",
    "font.size.lg",
    "font.size.xl",
    "font.size.display",
    "font.weight.medium",
    "font.weight.bold",
    "font.lineHeight.normal",
    "font.lineHeight.display",
  ],
  layoutTokens: [
    "breakpoint.compact",
    "breakpoint.medium",
    "grid.columnsCompact",
    "grid.gutterCompact",
    "spacing.sm",
    "spacing.md",
    "spacing.lg",
    "size.controlMd",
    "size.touchTarget",
    "size.bottomNavigation",
    "safeArea.bottomNavigation",
  ],
  protectedSemanticTokens: [
    "border.focus",
    "shadow.focus",
    "color.info",
    "color.success",
    "color.warning",
    "color.danger",
    "state.loading",
    "state.success",
    "state.warning",
    "state.error",
    "state.stale",
  ],
  supportedCapabilities: ["forced-colors", "reduced-motion", "low-power"],
  fallbackRecipeIds: ["forced-colors", "reduced-motion", "low-power"],
  priorityTokenRefs: [
    "role.worker.text",
    "role.worker.muted",
    "font.weight.bold",
    "size.touchTarget",
    "color.warning",
    "color.danger",
    "state.stale",
  ],
} as const satisfies RoleMaterialRecipe);

export const adminDenseOperationsRecipe = defineMaterialRecipe({
  id: "admin-dense-operations",
  role: "admin",
  sourceAuthority: "docs/design/figma/frames/admin/admin_dashboard_default_1-2875.png",
  readiness: "ready",
  density: "dense",
  viewportToken: "breakpoint.wide",
  surfaceTokens: [
    "role.admin.page",
    "role.admin.panel",
    "role.admin.text",
    "role.admin.muted",
    "surface.overlay",
    "surface.scrim",
  ],
  borderTokens: ["border.subtle", "border.strong", "border.focus"],
  typographyTokens: [
    "font.familySans",
    "font.familySerif",
    "font.familyMono",
    "font.numeric",
    "font.size.xs",
    "font.size.sm",
    "font.size.md",
    "font.size.lg",
    "font.size.xl",
    "font.weight.medium",
    "font.weight.bold",
    "font.lineHeight.tight",
    "font.lineHeight.normal",
  ],
  layoutTokens: [
    "breakpoint.medium",
    "breakpoint.wide",
    "grid.columnsWide",
    "grid.gutterWide",
    "grid.maxContent",
    "spacing.xs",
    "spacing.sm",
    "spacing.md",
    "size.controlSm",
    "size.controlMd",
    "size.touchTarget",
    "zIndex.sticky",
    "zIndex.overlay",
    "zIndex.modal",
  ],
  protectedSemanticTokens: [
    "border.focus",
    "shadow.focus",
    "text.onDanger",
    "text.onWarning",
    "text.onSuccess",
    "color.info",
    "color.success",
    "color.warning",
    "color.danger",
    "state.loading",
    "state.success",
    "state.warning",
    "state.error",
    "state.stale",
  ],
  supportedCapabilities: ["forced-colors", "reduced-motion", "low-power", "large-display"],
  fallbackRecipeIds: ["forced-colors", "reduced-motion", "low-power"],
  priorityTokenRefs: [
    "font.numeric",
    "font.lineHeight.tight",
    "size.controlSm",
    "grid.columnsWide",
    "grid.gutterWide",
    "border.focus",
    "color.danger",
    "state.stale",
  ],
} as const satisfies RoleMaterialRecipe);

export const oaReadinessRecipe = defineMaterialRecipe({
  id: "oa-readiness",
  role: "oa",
  sourceAuthority: "docs/design/figma/manifest.json#/exportUnavailable/2",
  readiness: "blocked",
  density: "dense",
  viewportToken: "breakpoint.wide",
  surfaceTokens: ["surface.page", "surface.panel", "surface.elevated", "surface.overlay", "surface.scrim"],
  borderTokens: ["border.subtle", "border.strong", "border.focus"],
  typographyTokens: [
    "font.familySans",
    "font.familyMono",
    "font.numeric",
    "font.size.sm",
    "font.size.md",
    "font.size.lg",
    "font.weight.medium",
    "font.weight.bold",
    "font.lineHeight.normal",
  ],
  layoutTokens: [
    "breakpoint.medium",
    "breakpoint.wide",
    "grid.columnsWide",
    "grid.gutterWide",
    "grid.maxContent",
    "size.controlSm",
    "size.controlMd",
    "size.touchTarget",
  ],
  protectedSemanticTokens: [
    "border.focus",
    "shadow.focus",
    "color.info",
    "color.success",
    "color.warning",
    "color.danger",
    "state.loading",
    "state.success",
    "state.warning",
    "state.error",
    "state.stale",
  ],
  supportedCapabilities: ["forced-colors", "reduced-motion", "low-power", "large-display"],
  fallbackRecipeIds: ["forced-colors", "reduced-motion", "low-power"],
  priorityTokenRefs: [
    "border.focus",
    "color.warning",
    "color.danger",
    "state.loading",
    "state.stale",
    "font.numeric",
  ],
} as const satisfies RoleMaterialRecipe);

export const dashboardReadinessRecipe = defineMaterialRecipe({
  id: "dashboard-readiness",
  role: "dashboard",
  sourceAuthority: "docs/design/figma/manifest.json#/exportUnavailable/1",
  readiness: "blocked",
  density: "wallboard",
  viewportToken: "breakpoint.wallboard",
  surfaceTokens: ["surface.page", "surface.panel", "surface.elevated", "surface.overlay", "surface.scrim"],
  borderTokens: ["border.subtle", "border.strong", "border.focus"],
  typographyTokens: [
    "font.familySans",
    "font.familyMono",
    "font.numeric",
    "font.size.md",
    "font.size.lg",
    "font.size.xl",
    "font.size.display",
    "font.weight.medium",
    "font.weight.bold",
    "font.lineHeight.display",
  ],
  layoutTokens: [
    "breakpoint.wide",
    "breakpoint.wallboard",
    "grid.columnsWide",
    "grid.gutterWide",
    "grid.maxContent",
    "spacing.md",
    "spacing.lg",
    "spacing.xl",
  ],
  protectedSemanticTokens: [
    "border.focus",
    "shadow.focus",
    "color.info",
    "color.success",
    "color.warning",
    "color.danger",
    "state.loading",
    "state.success",
    "state.warning",
    "state.error",
    "state.stale",
    "chart.axis",
    "chart.grid",
    "chart.threshold",
    "chart.positive",
    "chart.negative",
  ],
  supportedCapabilities: ["forced-colors", "reduced-motion", "low-power", "large-display"],
  fallbackRecipeIds: ["forced-colors", "reduced-motion", "low-power"],
  priorityTokenRefs: [
    "chart.axis",
    "chart.grid",
    "chart.threshold",
    "chart.positive",
    "chart.negative",
    "state.stale",
    "color.warning",
    "color.danger",
    "font.numeric",
    "font.size.display",
  ],
} as const satisfies RoleMaterialRecipe);

export const roleMaterialRecipes = Object.freeze({
  "worker-operational-dark": workerOperationalDarkRecipe,
  "admin-dense-operations": adminDenseOperationsRecipe,
  "oa-readiness": oaReadinessRecipe,
  "dashboard-readiness": dashboardReadinessRecipe,
}) satisfies Readonly<Record<NonCustomerMaterialRecipeId, RoleMaterialRecipe>>;
