import { createHash, randomUUID } from "node:crypto";
import type { PoolConnection } from "mysql2/promise";
import type { RequestContext } from "@xlb/types";
import { withTransaction } from "../../dal/transaction.js";
import {
  supportKnowledgeBaseRepository, type KbVersion, type SupportKnowledgeBaseRepositoryPort,
} from "./supportKnowledgeBaseRepository.js";

type TransactionRunner = <T>(fn:(connection:PoolConnection)=>Promise<T>)=>Promise<T>;
export class SupportKnowledgeBaseError extends Error { constructor(message:string,readonly statusCode=400){super(message);} }

function record(value:unknown):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw new SupportKnowledgeBaseError("object body required");return value as Record<string,unknown>;}
function text(value:unknown,name:string,min:number,max:number){if(typeof value!=="string")throw new SupportKnowledgeBaseError(`${name} must be a string`);const result=value.trim();if(result.length<min||result.length>max)throw new SupportKnowledgeBaseError(`${name} length is invalid`);return result;}
function optionalText(value:unknown,name:string,max:number){return value===undefined||value===null||value===""?null:text(value,name,1,max);}
function idempotency(value:unknown){return text(value,"idempotencyKey",8,128);}
function expectedVersion(value:unknown){const result=Number(value);if(!Number.isSafeInteger(result)||result<1)throw new SupportKnowledgeBaseError("expectedVersion is invalid");return result;}
function stringArray(value:unknown,name:string,maxItems=32){if(!Array.isArray(value)||value.length>maxItems)throw new SupportKnowledgeBaseError(`${name} must be a bounded array`);const result=value.map(item=>text(item,name,1,64).toLowerCase());if(new Set(result).size!==result.length)throw new SupportKnowledgeBaseError(`${name} contains duplicates`);return result;}
function hash(value:unknown){return createHash("sha256").update(JSON.stringify(value)).digest("hex");}
const id=(prefix:string)=>`${prefix}_${randomUUID().replaceAll("-","")}`;

export function validateKnowledgeMarkdown(value:unknown):string {
  const markdown=text(value,"bodyMarkdown",1,50_000);
  if (/<\/?(?:script|iframe|object|embed|style|form)\b|javascript\s*:|!\[[^\]]*\]\(\s*https?:\/\//iu.test(markdown)) {
    throw new SupportKnowledgeBaseError("knowledge content contains unsafe active or remote content");
  }
  if (/(?:请|需要|必须).{0,8}(?:提供|发送|输入).{0,8}(?:密码|验证码|完整银行卡|身份证号)|(?:send|provide|enter).{0,16}(?:password|verification code|full card number)/iu.test(markdown)) {
    throw new SupportKnowledgeBaseError("knowledge content requests restricted credentials");
  }
  return markdown;
}

function identity(context:RequestContext){if(context.appType!=="admin"||!context.userId||!context.cityCode||context.cityCode==="__global__")throw new SupportKnowledgeBaseError("real-city Admin identity required",403);return{city:context.cityCode,user:context.userId};}

export class SupportKnowledgeBaseService {
  constructor(private readonly repository:SupportKnowledgeBaseRepositoryPort=supportKnowledgeBaseRepository,
    private readonly transactionRunner:TransactionRunner=withTransaction){}

  private async role(c:PoolConnection,ctx:RequestContext,allowed:string[]){const i=identity(ctx);const role=await this.repository.loadAdminRole(c,i.city,i.user);if(!role||!allowed.includes(role))throw new SupportKnowledgeBaseError("current database role and explicit city scope do not permit this operation",403);return{...i,role};}

  async createArticle(context:RequestContext,body:unknown){const b=record(body);const slug=text(b.slug,"slug",2,128).toLowerCase();if(!/^[a-z0-9][a-z0-9_-]+$/.test(slug))throw new SupportKnowledgeBaseError("slug is invalid");const language=text(b.language,"language",2,32).toLowerCase();if(!/^[a-z]{2,8}(?:-[a-z0-9]{2,8}){0,3}$/.test(language))throw new SupportKnowledgeBaseError("language is invalid");const input={slug,language,categoryId:optionalText(b.categoryId,"categoryId",64),skuId:optionalText(b.skuId,"skuId",64),title:text(b.title,"title",1,200),summary:optionalText(b.summary,"summary",500),body:validateKnowledgeMarkdown(b.bodyMarkdown),keywords:stringArray(b.keywords,"keywords"),intentTags:stringArray(b.intentTags,"intentTags"),key:idempotency(b.idempotencyKey)};const fingerprint=hash(input);
    return this.transactionRunner(async c=>{const actor=await this.role(c,context,["admin","operator"]);const replay=await this.repository.findArticleByCreateKey(c,actor.city,actor.user,input.key);if(replay){if(replay.fingerprint!==fingerprint)throw new SupportKnowledgeBaseError("idempotency key was used with different content",409);const version=replay.article.currentDraftVersionId?await this.repository.findVersion(c,actor.city,replay.article.articleId,replay.article.currentDraftVersionId):null;return{article:replay.article,version,idempotent:true};}const articleId=id("kba"),versionId=id("kbv");await this.repository.insertArticle(c,{articleId,city:actor.city,slug:input.slug,language:input.language,categoryId:input.categoryId,skuId:input.skuId,user:actor.user,key:input.key,fingerprint});await this.repository.insertVersion(c,{versionId,city:actor.city,articleId,revision:1,title:input.title,summary:input.summary,body:input.body,keywords:input.keywords,intentTags:input.intentTags,user:actor.user,sha:hash({title:input.title,summary:input.summary,body:input.body,keywords:input.keywords,intentTags:input.intentTags})});if(!await this.repository.pointDraftCas(c,actor.city,articleId,versionId,1,input.key,fingerprint))throw new SupportKnowledgeBaseError("article version conflict",409);return{article:(await this.repository.findArticle(c,actor.city,articleId))!,version:(await this.repository.findVersion(c,actor.city,articleId,versionId))!,idempotent:false};});}

  async createRevision(context:RequestContext,articleId:string,body:unknown){const b=record(body);const input={expectedVersion:expectedVersion(b.expectedVersion),title:text(b.title,"title",1,200),summary:optionalText(b.summary,"summary",500),body:validateKnowledgeMarkdown(b.bodyMarkdown),keywords:stringArray(b.keywords,"keywords"),intentTags:stringArray(b.intentTags,"intentTags"),key:idempotency(b.idempotencyKey)};const fingerprint=hash(input);return this.transactionRunner(async c=>{const actor=await this.role(c,context,["admin","operator"]);const article=await this.repository.findArticle(c,actor.city,articleId,true);if(!article)throw new SupportKnowledgeBaseError("article not found",404);if(article.version!==input.expectedVersion)throw new SupportKnowledgeBaseError("article version conflict",409);const versionId=id("kbv"),revision=await this.repository.nextRevision(c,actor.city,articleId);await this.repository.insertVersion(c,{versionId,city:actor.city,articleId,revision,title:input.title,summary:input.summary,body:input.body,keywords:input.keywords,intentTags:input.intentTags,user:actor.user,sha:hash({title:input.title,summary:input.summary,body:input.body,keywords:input.keywords,intentTags:input.intentTags})});if(!await this.repository.pointDraftCas(c,actor.city,articleId,versionId,input.expectedVersion,input.key,fingerprint))throw new SupportKnowledgeBaseError("article version conflict",409);return{article:(await this.repository.findArticle(c,actor.city,articleId))!,version:(await this.repository.findVersion(c,actor.city,articleId,versionId))!};});}

  private async review(context:RequestContext,articleId:string,versionId:string,body:unknown,action:"submitted"|"approved"|"rejected") {const b=record(body);const key=idempotency(b.idempotencyKey),note=optionalText(b.note,"note",1000),fingerprint=hash({action,note,key});return this.transactionRunner(async c=>{const actor=await this.role(c,context,action==="submitted"?["admin","operator"]:["admin"]);const article=await this.repository.findArticle(c,actor.city,articleId,true);const version=await this.repository.findVersion(c,actor.city,articleId,versionId);if(!article||!version)throw new SupportKnowledgeBaseError("article version not found",404);const replay=await this.repository.findReviewReplay(c,actor.city,versionId,key);if(replay){if(replay.fingerprint!==fingerprint||replay.action!==action)throw new SupportKnowledgeBaseError("idempotency key was used with different review content",409);return{article,version,idempotent:true};}if(action!=="submitted"&&version.createdByAdminId===actor.user)throw new SupportKnowledgeBaseError("authors cannot review their own revision",403);const status:KbVersion["reviewStatus"]=action==="submitted"?"pending_review":action==="approved"?"approved":"rejected";if(!await this.repository.updateVersionReview(c,{city:actor.city,versionId,status,actor:actor.user,note}))throw new SupportKnowledgeBaseError("review state conflict",409);await this.repository.insertReviewEvent(c,{eventId:id("kbr"),city:actor.city,articleId,versionId,action,actor:actor.user,note,key,fingerprint});return{article,version:(await this.repository.findVersion(c,actor.city,articleId,versionId))!,idempotent:false};});}
  submitRevision(context:RequestContext,articleId:string,versionId:string,body:unknown){return this.review(context,articleId,versionId,body,"submitted");}
  approveRevision(context:RequestContext,articleId:string,versionId:string,body:unknown){return this.review(context,articleId,versionId,body,"approved");}
  rejectRevision(context:RequestContext,articleId:string,versionId:string,body:unknown){return this.review(context,articleId,versionId,body,"rejected");}

  async publishRevision(context:RequestContext,articleId:string,versionId:string,body:unknown){const b=record(body),input={expectedVersion:expectedVersion(b.expectedVersion),key:idempotency(b.idempotencyKey)},fingerprint=hash({articleId,versionId,...input});return this.transactionRunner(async c=>{const actor=await this.role(c,context,["admin"]);const article=await this.repository.findArticle(c,actor.city,articleId,true),version=await this.repository.findVersion(c,actor.city,articleId,versionId);if(!article||!version)throw new SupportKnowledgeBaseError("article version not found",404);if(version.reviewStatus!=="approved")throw new SupportKnowledgeBaseError("only an approved revision may be published",409);if(!await this.repository.publishCas(c,{city:actor.city,articleId,versionId,expectedVersion:input.expectedVersion,key:input.key,fingerprint}))throw new SupportKnowledgeBaseError("article version conflict",409);await this.repository.insertReviewEvent(c,{eventId:id("kbr"),city:actor.city,articleId,versionId,action:"published",actor:actor.user,note:null,key:input.key,fingerprint});return{article:(await this.repository.findArticle(c,actor.city,articleId))!,version};});}
}

export const supportKnowledgeBaseService = new SupportKnowledgeBaseService();
