import type { FastifyInstance } from "fastify";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { buildApp } from "../../backend/src/app.js";
import { getMysqlPool } from "../../backend/src/dal/mysqlPool.js";
import { bearerHeaders } from "./helpers/authTestHelper.js";

const nonce=`${Date.now()}${Math.random().toString(16).slice(2,8)}`;
const author=`p24e-author-${nonce}`,reviewer=`p24e-reviewer-${nonce}`,auditor=`p24e-auditor-${nonce}`;
const authorHeaders=bearerHeaders({appType:"admin",role:"admin",userId:author,cityCode:"hangzhou"});
const reviewerHeaders=bearerHeaders({appType:"admin",role:"admin",userId:reviewer,cityCode:"hangzhou"});
const auditorHeaders=bearerHeaders({appType:"admin",role:"auditor",userId:auditor,cityCode:"hangzhou"});
const customerHeaders=bearerHeaders({appType:"customer",role:"customer",userId:"customer-demo-001",cityCode:"hangzhou"});
describe("Phase 24E local Bot and knowledge base",{timeout:60_000},()=>{let app:FastifyInstance;let articleId="",versionId="";const conversations:string[]=[];
 beforeAll(async()=>{const pool=getMysqlPool();for(const[id,role]of[[author,"admin"],[reviewer,"admin"],[auditor,"auditor"]]as const){await pool.query(`INSERT INTO admin_users(id,username,role,city_scopes_json) VALUES(?,?,?,JSON_ARRAY('hangzhou')) ON DUPLICATE KEY UPDATE role=VALUES(role)`,[id,id,role]);await pool.query("INSERT IGNORE INTO admin_city_scopes(admin_user_id,city_code) VALUES(?,'hangzhou')",[id]);}app=await buildApp();await app.ready();});
 afterAll(async()=>{const pool=getMysqlPool();for(const id of conversations){await pool.query("DELETE FROM event_outbox WHERE aggregate_id=?",[id]);await pool.query("DELETE FROM support_bot_runs WHERE conversation_id=?",[id]);await pool.query("DELETE FROM support_messages WHERE conversation_id=?",[id]);await pool.query("DELETE FROM support_conversation_participants WHERE conversation_id=?",[id]);await pool.query("DELETE FROM support_conversations WHERE conversation_id=?",[id]);}if(articleId){await pool.query("UPDATE support_kb_articles SET current_draft_version_id=NULL,published_version_id=NULL WHERE article_id=?",[articleId]);await pool.query("DELETE FROM support_kb_review_events WHERE article_id=?",[articleId]);await pool.query("DELETE FROM support_kb_article_versions WHERE article_id=?",[articleId]);await pool.query("DELETE FROM support_kb_articles WHERE article_id=?",[articleId]);}await pool.query("DELETE FROM admin_city_scopes WHERE admin_user_id IN (?,?,?)",[author,reviewer,auditor]);await pool.query("DELETE FROM admin_users WHERE id IN (?,?,?)",[author,reviewer,auditor]);await app.close();});
 it("uses four-eyes approval and publishes one immutable city revision",async()=>{const created=await app.inject({method:"POST",url:"/api/internal/support/kb/articles",headers:authorHeaders,payload:{slug:`order-status-${nonce}`,language:"zh-cn",title:"查询订单进度",summary:"订单进度帮助",bodyMarkdown:"请在订单详情时间线查看最新进度。",keywords:["订单进度"],intentTags:["查询订单进度"],idempotencyKey:`p24e-create-${nonce}`}});expect(created.statusCode,created.body).toBe(200);articleId=created.json().article.articleId;versionId=created.json().version.articleVersionId;expect(created.json().article.version).toBe(2);
  const submitted=await app.inject({method:"POST",url:`/api/internal/support/kb/articles/${articleId}/versions/${versionId}/submit`,headers:authorHeaders,payload:{idempotencyKey:`p24e-submit-${nonce}`}});expect(submitted.statusCode,submitted.body).toBe(200);
  const self=await app.inject({method:"POST",url:`/api/internal/support/kb/articles/${articleId}/versions/${versionId}/approve`,headers:authorHeaders,payload:{idempotencyKey:`p24e-self-${nonce}`}});expect(self.statusCode).toBe(403);
  const approved=await app.inject({method:"POST",url:`/api/internal/support/kb/articles/${articleId}/versions/${versionId}/approve`,headers:reviewerHeaders,payload:{note:"Reviewed",idempotencyKey:`p24e-approve-${nonce}`}});expect(approved.statusCode,approved.body).toBe(200);
  const published=await app.inject({method:"POST",url:`/api/internal/support/kb/articles/${articleId}/publish`,headers:reviewerHeaders,payload:{versionId,expectedVersion:2,idempotencyKey:`p24e-publish-${nonce}`}});expect(published.statusCode,published.body).toBe(200);expect(published.json().article).toMatchObject({lifecycleStatus:"published",publishedVersionId:versionId,version:3});
  const denied=await app.inject({method:"POST",url:"/api/internal/support/kb/articles",headers:auditorHeaders,payload:{slug:`denied-${nonce}`,language:"zh-cn",title:"Denied",bodyMarkdown:"Denied",keywords:[],intentTags:[],idempotencyKey:`p24e-denied-${nonce}`}});expect(denied.statusCode).toBe(403);
 });
 async function conversation(text:string,suffix:string){const created=await app.inject({method:"POST",url:"/api/support/conversations",headers:customerHeaders,payload:{idempotencyKey:`p24e-conversation-${nonce}-${suffix}`}});expect(created.statusCode,created.body).toBe(200);const conversationId=created.json().conversation.conversationId;conversations.push(conversationId);const sent=await app.inject({method:"POST",url:`/api/support/conversations/${conversationId}/messages`,headers:customerHeaders,payload:{clientMessageId:`p24e-message-${nonce}-${suffix}`,textContent:text}});expect(sent.statusCode,sent.body).toBe(200);return{conversationId,messageId:sent.json().message.messageId};}
 it("replies only from the approved published revision and replays one Bot run",async()=>{const trigger=await conversation("查询订单进度","normal");const first=await app.inject({method:"POST",url:`/api/internal/support/bot/conversations/${trigger.conversationId}/messages/${trigger.messageId}/run`,headers:reviewerHeaders,payload:{}});expect(first.statusCode,first.body).toBe(200);expect(first.json().run).toMatchObject({decision:"reply",provider:"deterministic",externalProviderExecuted:false,matchedArticleVersionIds:[versionId]});const replay=await app.inject({method:"POST",url:`/api/internal/support/bot/conversations/${trigger.conversationId}/messages/${trigger.messageId}/run`,headers:reviewerHeaders,payload:{}});expect(replay.json().run.botRunId).toBe(first.json().run.botRunId);const [messages]=await getMysqlPool().query<any[]>("SELECT text_content,metadata_json FROM support_messages WHERE conversation_id=? AND sender_type='system'",[trigger.conversationId]);expect(messages).toHaveLength(1);expect(messages[0].text_content).toBe("请在订单详情时间线查看最新进度。");});
 it("forces sensitive financial text to handoff without a knowledge answer",async()=>{const trigger=await conversation("请帮我退款到银行卡","sensitive");const result=await app.inject({method:"POST",url:`/api/internal/support/bot/conversations/${trigger.conversationId}/messages/${trigger.messageId}/run`,headers:reviewerHeaders,payload:{}});expect(result.statusCode,result.body).toBe(200);expect(result.json().run).toMatchObject({decision:"hand_off",externalProviderExecuted:false,sensitiveClassification:"financial",matchedArticleVersionIds:[]});const [cv]=await getMysqlPool().query<any[]>("SELECT status FROM support_conversations WHERE conversation_id=?",[trigger.conversationId]);expect(cv[0].status).toBe("transferred");const [outbox]=await getMysqlPool().query<any[]>("SELECT payload_json FROM event_outbox WHERE aggregate_id=? AND event_type='support.bot.handed_off'",[trigger.conversationId]);expect(outbox).toHaveLength(1);expect(JSON.stringify(outbox[0].payload_json)).not.toContain("银行卡");});
});
