import type { PoolConnection, RowDataPacket } from "mysql2/promise";
export type SupportBotRun={botRunId:string;cityCode:string;conversationId:string;triggerMessageId:string;provider:string;providerStatus:string;externalProviderExecuted:false;providerRuleVersion:string;intent:string|null;confidenceBasisPoints:number;sensitiveClassification:string|null;decision:"reply"|"hand_off"|"no_match";reasonCodes:string[];matchedArticleVersionIds:string[];responseMessageId:string|null;createdAt:string};
type RunRow=RowDataPacket&{bot_run_id:string;city_code:string;conversation_id:string;trigger_message_id:string;provider:string;provider_status:string;external_provider_executed:number;provider_rule_version:string;intent:string|null;confidence_basis_points:number|string;sensitive_classification:string|null;decision:SupportBotRun["decision"];reason_codes_json:string|string[];matched_article_version_ids_json:string|string[];response_message_id:string|null;created_at:Date};const arr=(v:string|string[])=>Array.isArray(v)?v:JSON.parse(v) as string[];const map=(r:RunRow):SupportBotRun=>({botRunId:r.bot_run_id,cityCode:r.city_code,conversationId:r.conversation_id,triggerMessageId:r.trigger_message_id,provider:r.provider,providerStatus:r.provider_status,externalProviderExecuted:false,providerRuleVersion:r.provider_rule_version,intent:r.intent,confidenceBasisPoints:Number(r.confidence_basis_points),sensitiveClassification:r.sensitive_classification,decision:r.decision,reasonCodes:arr(r.reason_codes_json),matchedArticleVersionIds:arr(r.matched_article_version_ids_json),responseMessageId:r.response_message_id,createdAt:r.created_at.toISOString()});
export class SupportBotRepository{
 async findByTrigger(c:PoolConnection,city:string,conversationId:string,messageId:string){const[r]=await c.query<RunRow[]>(`SELECT * FROM support_bot_runs WHERE city_code=? AND conversation_id=? AND trigger_message_id=? LIMIT 1`,[city,conversationId,messageId]);return r[0]?map(r[0]):null;}
 async insert(c:PoolConnection,x:Omit<SupportBotRun,"createdAt">&{idempotencyKey:string}){await c.query(`INSERT INTO support_bot_runs(bot_run_id,city_code,conversation_id,trigger_message_id,provider,provider_status,external_provider_executed,provider_rule_version,intent,confidence_basis_points,sensitive_classification,decision,reason_codes_json,matched_article_version_ids_json,response_message_id,idempotency_key) VALUES(?,?,?,?,?,?,0,?,?,?,?,?,?,?,?,?)`,[x.botRunId,x.cityCode,x.conversationId,x.triggerMessageId,x.provider,x.providerStatus,x.providerRuleVersion,x.intent,x.confidenceBasisPoints,x.sensitiveClassification,x.decision,JSON.stringify(x.reasonCodes),JSON.stringify(x.matchedArticleVersionIds),x.responseMessageId,x.idempotencyKey]);}
 async requireAdminScope(c:PoolConnection,city:string,user:string){const[r]=await c.query<RowDataPacket[]>(`SELECT au.role FROM admin_users au INNER JOIN admin_city_scopes acs ON acs.admin_user_id=au.id AND (acs.city_code=? OR acs.city_code='__global__') WHERE au.id=? AND au.role IN ('admin','operator','auditor') LIMIT 1`,[city,user]);return r[0]?String(r[0].role):null;}
 async insertHandoffOutbox(c:PoolConnection,x:{eventId:string;city:string;conversationId:string;runId:string;reasonCodes:string[]}){await c.query(`INSERT INTO event_outbox(event_id,event_type,aggregate_type,aggregate_id,city_code,payload_json,status) VALUES(?,'support.bot.handed_off','support_conversation',?,?,?,'pending')`,[x.eventId,x.conversationId,x.city,JSON.stringify({cityCode:x.city,conversationId:x.conversationId,botRunId:x.runId,reasonCodes:x.reasonCodes,handedOffAt:new Date().toISOString()})]);}
}
export const supportBotRepository=new SupportBotRepository();
