import { randomUUID } from "node:crypto";
import type { CityCode, DispatchTask, GeoProviderEnvelope, RequestContext, WorkerLocation } from "@xlb/types";
import { upsertWorkerLocationSchema } from "@xlb/validators";
import type { RowDataPacket } from "mysql2/promise";
import { assertCityScopedContext } from "../dal/scopedExecutor.js";
import { getMysqlPool } from "../dal/mysqlPool.js";
import { geoProvider } from "./geoProvider.js";

const FRESH_MS = 10 * 60 * 1000;
export class WorkerLocationError extends Error { constructor(message:string,readonly statusCode=400){super(message);} }
type LocationRow=RowDataPacket&{location_id:string;worker_id:string;city_code:string;latitude:string;longitude:string;accuracy_meters:string;captured_at:Date;expires_at:Date;privacy_level:"private_exact";service_radius_km:string;location_sharing_enabled:number};
const map=(r:LocationRow):WorkerLocation=>({locationId:r.location_id,workerId:r.worker_id,cityCode:r.city_code as CityCode,latitude:Number(r.latitude),longitude:Number(r.longitude),accuracyMeters:Number(r.accuracy_meters),capturedAt:r.captured_at.toISOString(),expiresAt:r.expires_at.toISOString(),privacyLevel:r.privacy_level,serviceRadiusKm:Number(r.service_radius_km),locationSharingEnabled:Boolean(r.location_sharing_enabled),freshness:r.expires_at.getTime()>Date.now()?"fresh":"stale"});

export class WorkerLocationService {
  async adminBoard(context:RequestContext){const cityCode=assertCityScopedContext(context);if(context.appType!=="admin"||context.role!=="operator")throw new WorkerLocationError("dispatch board requires operator",403);const [rows]=await getMysqlPool().query<(RowDataPacket&{dispatch_task_id:string;order_id:string;sku_id:string;status:string;attempt_count:number;last_reason:string|null;offer_id:string|null;worker_id:string|null;offer_status:string|null;distance_km:string|null;eta_minutes:number|null;rank_score:string|null;expires_at:Date|null;location_freshness:string|null;external_executed:number})[]>(`SELECT dt.dispatch_task_id,dt.order_id,dt.sku_id,dt.status,dt.attempt_count,dt.last_reason,o.offer_id,o.worker_id,o.status offer_status,o.distance_km,o.eta_minutes,o.rank_score,o.expires_at,CASE WHEN wl.expires_at>CURRENT_TIMESTAMP THEN 'fresh' WHEN wl.location_id IS NULL THEN NULL ELSE 'stale' END location_freshness,COALESCE(JSON_EXTRACT(o.geo_provider_envelope_json,'$.externalProviderExecuted'),false) external_executed FROM dispatch_tasks dt LEFT JOIN dispatch_offers o ON o.city_code=dt.city_code AND o.dispatch_task_id=dt.dispatch_task_id LEFT JOIN worker_locations wl ON wl.city_code=o.city_code AND wl.worker_id=o.worker_id WHERE dt.city_code=? ORDER BY dt.created_at DESC,o.rank_score ASC LIMIT 200`,[cityCode]);return rows.map(r=>({dispatchTaskId:r.dispatch_task_id,orderId:r.order_id,skuId:r.sku_id,status:r.status,attemptCount:r.attempt_count,lastReason:r.last_reason,offer:r.offer_id?{offerId:r.offer_id,workerId:r.worker_id,status:r.offer_status,distanceKm:r.distance_km===null?null:Number(r.distance_km),etaMinutes:r.eta_minutes,rankScore:r.rank_score===null?null:Number(r.rank_score),expiresAt:r.expires_at?.toISOString()??null,locationFreshness:r.location_freshness,externalProviderExecuted:Boolean(r.external_executed)}:null}));}
  async upsert(context:RequestContext,body:unknown){
    const cityCode=assertCityScopedContext(context);if(context.appType!=="worker"||context.role!=="worker"||!context.userId)throw new WorkerLocationError("worker identity required",403);
    const parsed=upsertWorkerLocationSchema.safeParse(body);if(!parsed.success)throw new WorkerLocationError(parsed.error.message);
    const captured=new Date(parsed.data.capturedAt);const age=Date.now()-captured.getTime();if(age>FRESH_MS||age< -2*60*1000)throw new WorkerLocationError("location timestamp is stale or in the future",409);
    const expires=new Date(captured.getTime()+FRESH_MS);const pool=getMysqlPool();
    const [binding]=await pool.query<RowDataPacket[]>(`SELECT 1 FROM worker_city_bindings WHERE worker_id=? AND city_code=? AND is_enabled=1`,[context.userId,cityCode]);if(!binding[0])throw new WorkerLocationError("worker is not enabled in city",403);
    await pool.query(`INSERT INTO worker_dispatch_preferences(worker_id,city_code,service_radius_km,location_sharing_enabled) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE service_radius_km=VALUES(service_radius_km),location_sharing_enabled=VALUES(location_sharing_enabled)`,[context.userId,cityCode,parsed.data.serviceRadiusKm,parsed.data.locationSharingEnabled]);
    await pool.query(`INSERT INTO worker_locations(location_id,worker_id,city_code,latitude,longitude,accuracy_meters,captured_at,expires_at) VALUES(?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE location_id=VALUES(location_id),latitude=VALUES(latitude),longitude=VALUES(longitude),accuracy_meters=VALUES(accuracy_meters),captured_at=VALUES(captured_at),expires_at=VALUES(expires_at)`,[`wloc_${randomUUID().replaceAll("-","").slice(0,24)}`,context.userId,cityCode,parsed.data.latitude,parsed.data.longitude,parsed.data.accuracyMeters,captured,expires]);
    return this.getOwn(context);
  }
  async getOwn(context:RequestContext){const cityCode=assertCityScopedContext(context);if(context.appType!=="worker"||!context.userId)throw new WorkerLocationError("worker identity required",403);const [rows]=await getMysqlPool().query<LocationRow[]>(`SELECT wl.*,p.service_radius_km,p.location_sharing_enabled FROM worker_locations wl JOIN worker_dispatch_preferences p ON p.worker_id=wl.worker_id AND p.city_code=wl.city_code WHERE wl.worker_id=? AND wl.city_code=?`,[context.userId,cityCode]);return rows[0]?map(rows[0]):null;}
  async rankCandidates(context:RequestContext,task:DispatchTask,exclude:string[],limit=3){
    const cityCode=assertCityScopedContext(context);const pool=getMysqlPool();const [addresses]=await pool.query<(RowDataPacket&{address:string})[]>(`SELECT CONCAT_WS(' ',o.address_province,o.address_city,o.address_district,o.detail_address) address FROM dispatch_tasks dt JOIN orders o ON o.city_code=dt.city_code AND o.order_id=dt.order_id WHERE dt.city_code=? AND dt.dispatch_task_id=?`,[cityCode,task.dispatchTaskId]);const target=await geoProvider.geocode(cityCode,addresses[0]?.address??task.orderId);
    await pool.query(`UPDATE dispatch_tasks SET target_latitude=?,target_longitude=?,geo_provider_envelope_json=? WHERE city_code=? AND dispatch_task_id=?`,[target.latitude,target.longitude,JSON.stringify({provider:"local_mock",providerStatus:"geocoded_mock",externalProviderExecuted:false}),cityCode,task.dispatchTaskId]);
    const params:unknown[]=[cityCode,cityCode,cityCode,task.skuId,cityCode];const exclusion=exclude.length?`AND wp.worker_id NOT IN (${exclude.map(()=>"?").join(",")})`:"";params.push(...exclude);
    const [rows]=await pool.query<(RowDataPacket&{worker_id:string;latitude:string;longitude:string;service_radius_km:string;rating_score:string;penalty_score:string})[]>(`SELECT wp.worker_id,wl.latitude,wl.longitude,p.service_radius_km,p.rating_score,p.penalty_score FROM worker_profiles wp JOIN worker_city_bindings b ON b.worker_id=wp.worker_id AND b.city_code=? AND b.is_enabled=1 JOIN worker_online_status os ON os.worker_id=wp.worker_id AND os.city_code=? AND os.is_online=1 JOIN worker_qualifications q ON q.worker_id=wp.worker_id AND q.city_code=? AND q.sku_id=? AND q.is_eligible=1 JOIN worker_locations wl ON wl.worker_id=wp.worker_id AND wl.city_code=? AND wl.expires_at>CURRENT_TIMESTAMP JOIN worker_dispatch_preferences p ON p.worker_id=wl.worker_id AND p.city_code=wl.city_code AND p.location_sharing_enabled=1 WHERE wp.status='active' AND wp.dispatch_status='available' AND wp.is_certified=1 ${exclusion}`,[...params]);
    const ranked=[] as Array<{workerId:string;distanceKm:number;etaMinutes:number;rankScore:number;envelope:GeoProviderEnvelope}>;for(const row of rows){const envelope=await geoProvider.route({latitude:Number(row.latitude),longitude:Number(row.longitude)},target);if(envelope.distanceKm>Number(row.service_radius_km))continue;ranked.push({workerId:row.worker_id,distanceKm:envelope.distanceKm,etaMinutes:envelope.etaMinutes,rankScore:envelope.distanceKm*100+Number(row.penalty_score)*10-Number(row.rating_score),envelope});}return ranked.sort((a,b)=>a.rankScore-b.rankScore||a.workerId.localeCompare(b.workerId)).slice(0,limit);
  }
}
export const workerLocationService=new WorkerLocationService();
