-- Phase 3A-1: Disable demo catalog entries (audit-retained, not deleted)
-- Generated by scripts/generate-official-catalog-seeds.mjs

UPDATE service_categories SET is_enabled = 0 WHERE category_id = 'demo_cleaning_category';
UPDATE service_items SET is_enabled = 0 WHERE item_id = 'demo_cleaning_item';
UPDATE service_skus SET is_enabled = 0 WHERE sku_id = 'demo_cleaning_sku';
UPDATE price_rules SET is_enabled = 0 WHERE sku_id = 'demo_cleaning_sku' OR price_rule_id LIKE 'demo_price_%';
