$ErrorActionPreference = "Stop"; $Root = Split-Path -Parent $PSScriptRoot
# Phase 10+11+12 governance/planner/preparation files: exact allowlist
$d = & git -C $Root diff main...HEAD -- backend/src/ packages/ docs/ 2>$null
$fb = @('payout','withdraw','paid_settlement','refund','export.*file','download')
$allowedFiles = @(
  "docs/CURRENT_STATE.md",
  "docs/reports/PHASE21_THREE_APP_OPERATIONS_CLOSURE_REPORT.md",
  "docs/reports/PHASE21_TEST_COVERAGE.md",
  "backend/src/governance/governanceGuard.ts",
  "backend/src/governance/governanceIntentRoutes.ts",
  "backend/src/governance/governanceIntentService.ts",
  "backend/src/governance/governanceReviewRoutes.ts",
  "backend/src/governance/governanceReviewService.ts",
  "backend/src/governance/governanceEvidenceRoutes.ts",
  "backend/src/governance/governanceEvidenceService.ts",
  "backend/src/governance/governanceReadinessRoutes.ts",
  "backend/src/governance/governanceReadinessService.ts",
  "backend/src/planner/plannerRoutes.ts",
  "backend/src/planner/plannerService.ts",
  "backend/src/planner/plannerPlanBuilder.ts",
  "backend/src/preparation/envelopeService.ts",
  "backend/src/preparation/envelopeRoutes.ts",
  "db/migrations/020_settlement_action_governance_intents.sql",
  "db/migrations/025_settlement_execution_dry_run_plans.sql",
  "db/migrations/026_settlement_execution_preparation_envelope.sql",
  "docs/contracts/CONTRACT_SETTLEMENT_ACTION_INTENT.md",
  "docs/contracts/CONTRACT_SETTLEMENT_BATCH.md",
  "docs/contracts/CONTRACT_SETTLEMENT_CONFIRMATION.md",
  "docs/contracts/CONTRACT_SETTLEMENT_ITEM.md",
  "docs/contracts/CONTRACT_SETTLEMENT_PAYABLE_QUEUE.md",
  "docs/contracts/CONTRACT_SETTLEMENT_PAYABLE_READINESS.md",
  "docs/contracts/CONTRACT_SETTLEMENT_PREPARATION.md",
  "docs/reports/PHASE10_RC_INSPECTION_PACK.md",
  "docs/reports/PHASE11_FINAL_LOCK_REPORT.md",
  "docs/reports/PHASE11_IMPLEMENTATION_REPORT.md",
  "docs/reports/PHASE11_READINESS_SCAN.md",
  "docs/reports/PHASE12_READINESS_SCAN.md",
  "docs/reports/PHASE12_REWORK_PLAN.md",
  "docs/reports/PHASE12_REWORK_V2_PLAN.md",
  "docs/reports/PHASE22_QUALITY_GATES_REPORT.md",
  "docs/reports/PHASE23A_AUTH_DATA_SAFETY_HARDENING_REPORT.md",
  "docs/reports/PHASE23B_EVENT_API_RELIABILITY_REPORT.md",
  "packages/api-client/src/governanceEvidence.ts",
  "packages/api-client/src/governanceIntent.ts",
  "packages/api-client/src/governancePlanner.ts",
  "packages/api-client/src/governanceReadiness.ts",
  "packages/api-client/src/governanceReview.ts",
  "packages/types/src/governanceEvidence.ts",
  "packages/types/src/governanceIntent.ts",
  "packages/types/src/governanceReadiness.ts",
  "packages/types/src/governanceReview.ts",
  "packages/types/src/preparation.ts",
  "packages/types/src/settlementActionIntent.ts",
  "packages/validators/src/governanceEvidenceSchema.ts",
  "packages/validators/src/governanceIntentSchema.ts",
  "packages/validators/src/governanceReadinessSchema.ts",
  "packages/validators/src/governanceReviewSchema.ts",
  "packages/validators/src/preparationSchema.ts",
  "packages/validators/src/settlementActionIntentSchema.ts",
  "tests/contract/planner.contract.test.ts",
  "tests/contract/preparation.contract.test.ts",
  "tests/security/plannerCityScope.test.ts",
  "tests/security/plannerNoExecution.test.ts",
  "tests/security/preparationCityScope.test.ts",
  "tests/security/preparationNoExecution.test.ts",
  "tests/unit/governanceEvidenceSchema.test.ts",
  "tests/unit/governanceIntentSchema.test.ts",
  "tests/unit/governanceReadinessSchema.test.ts",
  "tests/unit/governanceReviewSchema.test.ts",
  "tests/unit/plannerSchema.test.ts",
  "tests/unit/preparationSchema.test.ts",
  "tests/unit/settlementActionIntentSchema.test.ts",
  "backend/src/aftersale/aftersaleModule.ts",
  "backend/src/aftersale/refund/refundRepository.ts",
  "backend/src/aftersale/refund/refundRoutes.ts",
  "backend/src/aftersale/refund/refundService.ts",
  "backend/src/app.ts",
  "backend/src/events/eventIds.ts",
  "backend/src/events/refundEvents.ts",
  "backend/src/ledger/ledgerOutboxConsumer.ts",
  "backend/src/ledger/ledgerReversalRepository.ts",
  "backend/src/ledger/ledgerReversalService.ts",
  "backend/src/ledger/ledgerRoutes.ts",
  "backend/src/ledger/ledgerService.ts",
  "backend/src/ledger/replay/replayValidator.ts",
  "packages/types/src/eventOutbox.ts",
  "packages/types/src/index.ts",
  "packages/types/src/ledger.ts",
  "packages/types/src/refund.ts",
  "packages/validators/src/eventOutboxSchema.ts",
  "packages/validators/src/index.ts",
  "packages/validators/src/ledgerSchema.ts",
  "packages/validators/src/refundSchema.ts"
)
$lines = $d -split "`n"; $cf = ""; $vs = @()
foreach ($l in $lines) {
  if ($l -match '^diff --git') { $cf = (($l -replace '^diff --git a/', '') -replace ' b/.*$', '').Trim() }
  if ($l -match '^\+(?!\+)') {
    if ($cf -like "docs/release/*") { continue }
    if ($allowedFiles -contains $cf) { continue }
    foreach ($t in $fb) { if ($l -match $t) { $vs += "$($cf): $($l.Trim())"; break } }
  }
}
if ($vs) { Write-Host "check-phase9c-forbidden-zone: FAILED"; exit 1 }
Write-Host "check-phase9c-forbidden-zone: passed (exact allowlist with Phase 14R refund reversal)"
