import { randomUUID } from "node:crypto";
import type { PoolConnection, ResultSetHeader, RowDataPacket } from "mysql2/promise";

export type BotTrigger = { conversationId:string;messageId:string;status:string;version:number;lastServerSeq:number;text:string };

export class SupportBotConversationGateway {
  async loadRequesterTrigger(c:PoolConnection,city:string,conversationId:string,messageId:string):Promise<BotTrigger|null>{const [r]=await c.query<(RowDataPacket&{conversation_id:string;message_id:string;status:string;version:number|string;last_server_seq:number|string;text_content:string})[]>(`SELECT cv.conversation_id,m.message_id,cv.status,cv.version,cv.last_server_seq,m.text_content FROM support_conversations cv INNER JOIN support_messages m ON m.city_code=cv.city_code AND m.conversation_id=cv.conversation_id WHERE cv.city_code=? AND cv.conversation_id=? AND m.message_id=? AND m.sender_type IN ('customer','worker') AND m.message_type='text' LIMIT 1 FOR UPDATE`,[city,conversationId,messageId]);return r[0]?{conversationId:r[0].conversation_id,messageId:r[0].message_id,status:r[0].status,version:Number(r[0].version),lastServerSeq:Number(r[0].last_server_seq),text:r[0].text_content}:null;}
  async appendBotReply(c:PoolConnection,input:{city:string;trigger:BotTrigger;text:string;metadata:Record<string,unknown>}){const messageId=`smsg_${randomUUID()}`,seq=input.trigger.lastServerSeq+1;const [u]=await c.query<ResultSetHeader>(`UPDATE support_conversations SET last_server_seq=?,version=version+1 WHERE city_code=? AND conversation_id=? AND version=? AND status='queueing'`,[seq,input.city,input.trigger.conversationId,input.trigger.version]);if(u.affectedRows!==1)return null;await c.query(`INSERT INTO support_messages(message_id,city_code,conversation_id,sender_type,sender_id,client_message_id,server_seq,message_type,text_content,metadata_json) VALUES(?,?,?,'system',NULL,?,?,'system',?,?)`,[messageId,input.city,input.trigger.conversationId,`bot-run:${input.trigger.messageId}`,seq,input.text,JSON.stringify(input.metadata)]);return messageId;}
  async handOff(c:PoolConnection,input:{city:string;trigger:BotTrigger;reasonCodes:string[]}){const messageId=`smsg_${randomUUID()}`,seq=input.trigger.lastServerSeq+1;const [u]=await c.query<ResultSetHeader>(`UPDATE support_conversations SET status='transferred',last_server_seq=?,version=version+1 WHERE city_code=? AND conversation_id=? AND version=? AND status='queueing'`,[seq,input.city,input.trigger.conversationId,input.trigger.version]);if(u.affectedRows!==1)return null;await c.query(`INSERT INTO support_messages(message_id,city_code,conversation_id,sender_type,sender_id,client_message_id,server_seq,message_type,text_content,metadata_json) VALUES(?,?,?,'system',NULL,?,?,'system',?,?)`,[messageId,input.city,input.trigger.conversationId,`bot-handoff:${input.trigger.messageId}`,seq,"已转接人工客服，请稍候。",JSON.stringify({kind:"bot_handoff",reasonCodes:input.reasonCodes})]);return messageId;}
}
export const supportBotConversationGateway = new SupportBotConversationGateway();
