import type { PoolConnection, RowDataPacket } from "mysql2/promise";

export type ConversationRow = { conversationId:string;cityCode:string;source:"customer"|"worker";requesterId:string;status:string;assignedAgentId:string|null;lastServerSeq:number;version:number };
export type MessageRow = { messageId:string;conversationId:string;senderType:string;senderId:string|null;clientMessageId:string;serverSeq:number;messageType:string;textContent:string|null;mediaAssetId:string|null;createdAt:string };
type CRow=RowDataPacket&{conversation_id:string;city_code:string;source:"customer"|"worker";requester_id:string;status:string;assigned_agent_id:string|null;last_server_seq:number|string;version:number|string};
type MRow=RowDataPacket&{message_id:string;conversation_id:string;sender_type:string;sender_id:string|null;client_message_id:string;server_seq:number|string;message_type:string;text_content:string|null;media_asset_id:string|null;created_at:Date};
const mapC=(r:CRow):ConversationRow=>({conversationId:r.conversation_id,cityCode:r.city_code,source:r.source,requesterId:r.requester_id,status:r.status,assignedAgentId:r.assigned_agent_id,lastServerSeq:Number(r.last_server_seq),version:Number(r.version)});
const mapM=(r:MRow):MessageRow=>({messageId:r.message_id,conversationId:r.conversation_id,senderType:r.sender_type,senderId:r.sender_id,clientMessageId:r.client_message_id,serverSeq:Number(r.server_seq),messageType:r.message_type,textContent:r.text_content,mediaAssetId:r.media_asset_id,createdAt:r.created_at.toISOString()});

export class SupportConversationRepository {
  async findByCreateKey(c:PoolConnection,city:string,source:string,requester:string,key:string){const [r]=await c.query<CRow[]>(`SELECT * FROM support_conversations WHERE city_code=? AND source=? AND requester_id=? AND create_idempotency_key=? LIMIT 1`,[city,source,requester,key]);return r[0]?mapC(r[0]):null;}
  async insert(c:PoolConnection,x:{id:string;city:string;source:string;requester:string;key:string}){await c.query(`INSERT INTO support_conversations(conversation_id,city_code,source,requester_id,create_idempotency_key) VALUES(?,?,?,?,?)`,[x.id,x.city,x.source,x.requester,x.key]);await c.query(`INSERT INTO support_conversation_participants(city_code,conversation_id,participant_type,participant_id) VALUES(?,?,?,?)`,[x.city,x.id,x.source,x.requester]);}
  async find(c:PoolConnection,city:string,id:string,lock=false){const [r]=await c.query<CRow[]>(`SELECT * FROM support_conversations WHERE city_code=? AND conversation_id=? LIMIT 1${lock?" FOR UPDATE":""}`,[city,id]);return r[0]?mapC(r[0]):null;}
  async isParticipant(c:PoolConnection,city:string,id:string,type:string,user:string){const [r]=await c.query<RowDataPacket[]>(`SELECT 1 FROM support_conversation_participants WHERE city_code=? AND conversation_id=? AND participant_type=? AND participant_id=? AND left_at IS NULL LIMIT 1`,[city,id,type,user]);return !!r[0];}
  async findMessageByClient(c:PoolConnection,city:string,id:string,key:string){const [r]=await c.query<MRow[]>(`SELECT * FROM support_messages WHERE city_code=? AND conversation_id=? AND client_message_id=? LIMIT 1`,[city,id,key]);return r[0]?mapM(r[0]):null;}
  async insertMessage(c:PoolConnection,x:{id:string;city:string;conversationId:string;senderType:string;senderId:string|null;clientId:string;seq:number;text:string;messageType?:"text"|"system"}){await c.query(`INSERT INTO support_messages(message_id,city_code,conversation_id,sender_type,sender_id,client_message_id,server_seq,message_type,text_content) VALUES(?,?,?,?,?,?,?,?,?)`,[x.id,x.city,x.conversationId,x.senderType,x.senderId,x.clientId,x.seq,x.messageType??"text",x.text]);await c.query(`UPDATE support_conversations SET last_server_seq=?,version=version+1 WHERE city_code=? AND conversation_id=?`,[x.seq,x.city,x.conversationId]);}
  async messagesAfter(c:PoolConnection,city:string,id:string,after:number,limit:number){const [r]=await c.query<MRow[]>(`SELECT * FROM support_messages WHERE city_code=? AND conversation_id=? AND server_seq>? ORDER BY server_seq ASC LIMIT ?`,[city,id,after,limit]);return r.map(mapM);}
  async accept(c:PoolConnection,city:string,id:string,admin:string,version:number){const [p]=await c.query<RowDataPacket[]>(`SELECT 1 FROM support_agents WHERE city_code=? AND admin_user_id=? AND lifecycle_status='active' AND work_status='online' LIMIT 1`,[city,admin]);if(!p[0])return false;const [r]=await c.query<any>(`UPDATE support_conversations SET status='active',assigned_agent_id=?,accepted_at=CURRENT_TIMESTAMP(3),version=version+1 WHERE city_code=? AND conversation_id=? AND status='queueing' AND version=?`,[admin,city,id,version]);if(r.affectedRows!==1)return false;await c.query(`INSERT INTO support_conversation_participants(city_code,conversation_id,participant_type,participant_id) VALUES(?,?,'agent',?) ON DUPLICATE KEY UPDATE left_at=NULL`,[city,id,admin]);return true;}
  async transfer(c:PoolConnection,city:string,id:string,fromAdmin:string,toAdmin:string,version:number){const [p]=await c.query<RowDataPacket[]>(`SELECT 1 FROM support_agents WHERE city_code=? AND admin_user_id=? AND lifecycle_status='active' LIMIT 1`,[city,toAdmin]);if(!p[0])return false;const [r]=await c.query<any>(`UPDATE support_conversations SET status='transferred',assigned_agent_id=?,version=version+1 WHERE city_code=? AND conversation_id=? AND assigned_agent_id=? AND status IN ('active','transferred') AND version=?`,[toAdmin,city,id,fromAdmin,version]);if(r.affectedRows!==1)return false;await c.query(`UPDATE support_conversation_participants SET left_at=CURRENT_TIMESTAMP(3),version=version+1 WHERE city_code=? AND conversation_id=? AND participant_type='agent' AND participant_id=? AND left_at IS NULL`,[city,id,fromAdmin]);await c.query(`INSERT INTO support_conversation_participants(city_code,conversation_id,participant_type,participant_id) VALUES(?,?,'agent',?) ON DUPLICATE KEY UPDATE left_at=NULL,version=version+1`,[city,id,toAdmin]);return true;}
  async close(c:PoolConnection,city:string,id:string,admin:string,version:number){const [r]=await c.query<any>(`UPDATE support_conversations SET status='closed',closed_at=CURRENT_TIMESTAMP(3),version=version+1 WHERE city_code=? AND conversation_id=? AND assigned_agent_id=? AND status IN ('active','transferred') AND version=?`,[city,id,admin,version]);return r.affectedRows===1;}
}
export const supportConversationRepository=new SupportConversationRepository();
