import { randomUUID } from "node:crypto";
import type { RequestContext } from "@xlb/types";
import { withTransaction } from "../../dal/transaction.js";
import { supportConversationRepository as repo } from "./supportConversationRepository.js";
import { eventOutboxRepository } from "../../events/eventOutbox.js";
import { generateEventId } from "../../events/eventIds.js";
import type { PoolConnection } from "mysql2/promise";
import { canAccessAdminOperation } from "../../auth/operationsAuthorization.js";
export class SupportConversationError extends Error{constructor(message:string,readonly statusCode=400){super(message)}}
function identity(ctx:RequestContext){if(!ctx.cityCode||ctx.cityCode==="__global__"||!ctx.userId)throw new SupportConversationError("real city and identity required",403);if(ctx.appType==="customer"&&ctx.role==="customer")return{city:ctx.cityCode,type:"customer" as const,user:ctx.userId};if(ctx.appType==="worker"&&ctx.role==="worker")return{city:ctx.cityCode,type:"worker" as const,user:ctx.userId};if(canAccessAdminOperation(ctx,["admin","operator"]))return{city:ctx.cityCode,type:"agent" as const,user:ctx.userId};throw new SupportConversationError("role is not allowed",403)}
function obj(v:unknown){if(!v||typeof v!=="object"||Array.isArray(v))throw new SupportConversationError("object body required");return v as Record<string,unknown>}
export class SupportConversationService{
 private outbox(c:PoolConnection,eventType:"support.conversation.started"|"support.conversation.transferred"|"support.conversation.closed"|"support.message.created",cityCode:string,aggregateId:string,payload:Record<string,unknown>){return eventOutboxRepository.insertEvent(c,{eventId:generateEventId(),eventType,aggregateType:eventType==="support.message.created"?"support_message":"support_conversation",aggregateId,cityCode,payload});}
 async create(ctx:RequestContext,body:unknown){const i=identity(ctx);if(i.type==="agent")throw new SupportConversationError("requester required",403);const b=obj(body),key=String(b.idempotencyKey??"");if(key.length<8||key.length>128)throw new SupportConversationError("invalid idempotencyKey");return withTransaction(async c=>{const old=await repo.findByCreateKey(c,i.city,i.type,i.user,key);if(old)return old;const id=`scv_${randomUUID()}`;await repo.insert(c,{id,city:i.city,source:i.type,requester:i.user,key});await this.outbox(c,"support.conversation.started",i.city,id,{conversationId:id,cityCode:i.city,source:i.type});return (await repo.find(c,i.city,id))!;});}
 async send(ctx:RequestContext,id:string,body:unknown){const i=identity(ctx),b=obj(body),clientId=String(b.clientMessageId??""),text=String(b.textContent??"").trim();if(clientId.length<8||clientId.length>128||text.length<1||text.length>4000)throw new SupportConversationError("invalid message");return withTransaction(async c=>{const cv=await repo.find(c,i.city,id,true);if(!cv)throw new SupportConversationError("conversation not found",404);if(cv.status==="closed")throw new SupportConversationError("conversation closed",409);if(!await repo.isParticipant(c,i.city,id,i.type,i.user))throw new SupportConversationError("not a participant",403);const old=await repo.findMessageByClient(c,i.city,id,clientId);if(old)return old;const seq=cv.lastServerSeq+1,messageId=`smsg_${randomUUID()}`;await repo.insertMessage(c,{id:messageId,city:i.city,conversationId:id,senderType:i.type,senderId:i.user,clientId,seq,text});await this.outbox(c,"support.message.created",i.city,messageId,{conversationId:id,messageId,serverSeq:seq,messageType:"text"});return (await repo.findMessageByClient(c,i.city,id,clientId))!;});}
 async messages(ctx:RequestContext,id:string,after=0,limit=100){const i=identity(ctx);return withTransaction(async c=>{if(!await repo.isParticipant(c,i.city,id,i.type,i.user))throw new SupportConversationError("not a participant",403);return repo.messagesAfter(c,i.city,id,Math.max(0,after),Math.min(100,Math.max(1,limit)));});}
 async accept(ctx:RequestContext,id:string,body:unknown){const i=identity(ctx);if(i.type!=="agent")throw new SupportConversationError("agent required",403);const version=Number(obj(body).expectedVersion);return withTransaction(async c=>{if(!Number.isSafeInteger(version)||!await repo.accept(c,i.city,id,i.user,version))throw new SupportConversationError("accept conflict or inactive agent",409);return (await repo.find(c,i.city,id))!;});}
 async appendSystemMessage(input:{cityCode:string;conversationId:string;clientMessageId:string;textContent:string}){if(!input.cityCode||input.cityCode==="__global__"||input.textContent.length<1||input.textContent.length>4000)throw new SupportConversationError("invalid system message");return withTransaction(async c=>{const cv=await repo.find(c,input.cityCode,input.conversationId,true);if(!cv)throw new SupportConversationError("conversation not found",404);if(cv.status==="closed")throw new SupportConversationError("conversation closed",409);const old=await repo.findMessageByClient(c,input.cityCode,input.conversationId,input.clientMessageId);if(old)return old;const messageId=`smsg_${randomUUID()}`,seq=cv.lastServerSeq+1;await repo.insertMessage(c,{id:messageId,city:input.cityCode,conversationId:input.conversationId,senderType:"system",senderId:null,clientId:input.clientMessageId,seq,text:input.textContent,messageType:"system"});await this.outbox(c,"support.message.created",input.cityCode,messageId,{conversationId:input.conversationId,messageId,serverSeq:seq,messageType:"system"});return (await repo.findMessageByClient(c,input.cityCode,input.conversationId,input.clientMessageId))!;});}
 async transfer(ctx:RequestContext,id:string,body:unknown){const i=identity(ctx),b=obj(body);if(i.type!=="agent")throw new SupportConversationError("agent required",403);const expectedVersion=Number(b.expectedVersion),to=String(b.assignedAgentId??"");return withTransaction(async c=>{if(!Number.isSafeInteger(expectedVersion)||!to||!await repo.transfer(c,i.city,id,i.user,to,expectedVersion))throw new SupportConversationError("transfer conflict or invalid target",409);await this.outbox(c,"support.conversation.transferred",i.city,id,{conversationId:id,fromAgentId:i.user,toAgentId:to});return (await repo.find(c,i.city,id))!;});}
 async close(ctx:RequestContext,id:string,body:unknown){const i=identity(ctx),version=Number(obj(body).expectedVersion);if(i.type!=="agent")throw new SupportConversationError("agent required",403);return withTransaction(async c=>{if(!Number.isSafeInteger(version)||!await repo.close(c,i.city,id,i.user,version))throw new SupportConversationError("close conflict",409);await this.outbox(c,"support.conversation.closed",i.city,id,{conversationId:id,closedBy:i.user});return (await repo.find(c,i.city,id))!;});}
}
export const supportConversationService=new SupportConversationService();
