{{- range $name, $frontend := .Values.frontends }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xlb.fullname" $ }}-{{ $name }}
  labels:
    {{- include "xlb.componentLabels" (dict "root" $ "component" $name) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "xlb.selectorLabels" (dict "root" $ "component" $name) | nindent 4 }}
  ports:
    - name: http
      port: 4173
      targetPort: http
      protocol: TCP
{{- end }}
