import { describe, expect, it } from "vitest";
import { readinessPacketStatusSchema, createReadinessPacketRequestSchema, governanceReadinessPacketRecordSchema } from "@xlb/validators";

describe("Phase 10F — Governance Readiness Packet Schema", () => {
  describe("unit — valid", () => {
    it("accepts allowed statuses", () => ["draft","checks_pending","blocked","ready_for_future_phase_review","archived"].forEach(s => expect(readinessPacketStatusSchema.safeParse(s).success).toBe(true)));
    it("accepts valid create", () => expect(createReadinessPacketRequestSchema.safeParse({ cityCode:"hz",intentId:"gi_1",createdByAdminId:"a" }).success).toBe(true));
    it("accepts valid record with all false execution boundary", () => expect(governanceReadinessPacketRecordSchema.safeParse({ id:"rp_1",cityCode:"hz",intentId:"gi_1",reviewId:null,evidenceBundleId:null,statementId:null,packetStatus:"draft",readinessChecks:{},blockerFlags:[],riskFlags:[],sourceRefs:[],dryRunGuard:{dryRunMode:"governance_guard_only",executionSimulationEnabled:false,moneyMovementSimulationEnabled:false,providerSimulationEnabled:false,ledgerSimulationEnabled:false,refundSimulationEnabled:false,fileGenerationSimulationEnabled:false,guardReason:"test",nextAllowedPhase:"Phase 11"},executionBoundary:{governanceOnly:true,executionEnabled:false,mutationEnabled:false,payoutEnabled:false,refundExecutionEnabled:false,ledgerMutationEnabled:false,settlementMutationEnabled:false,fileGenerationEnabled:false,downloadEnabled:false,providerDispatchEnabled:false},createdByAdminId:"a",createdAt:"2025-01-01T00:00:00Z",updatedAt:"2025-01-01T00:00:00Z",archivedAt:null}).success).toBe(true));
  });
  describe("unit — forbidden statuses", () => ["ready_to_execute","executing","executed","paid","refunded","reversed","settled","exported","downloaded","generated"].forEach(s => it(`rejects ${s}`,()=>expect(readinessPacketStatusSchema.safeParse(s).success).toBe(false))));
  describe("unit — boundary false-true violations", () => {
    const fields = ["executionEnabled","mutationEnabled","payoutEnabled","refundExecutionEnabled","ledgerMutationEnabled","settlementMutationEnabled","fileGenerationEnabled","downloadEnabled","providerDispatchEnabled"];
    fields.forEach(f => it(`rejects execution boundary ${f}:true`,()=>{const b:Record<string,unknown>={governanceOnly:true,executionEnabled:false,mutationEnabled:false,payoutEnabled:false,refundExecutionEnabled:false,ledgerMutationEnabled:false,settlementMutationEnabled:false,fileGenerationEnabled:false,downloadEnabled:false,providerDispatchEnabled:false};b[f]=true;expect(governanceReadinessPacketRecordSchema.safeParse({id:"rp_1",cityCode:"hz",intentId:"gi_1",reviewId:null,evidenceBundleId:null,statementId:null,packetStatus:"draft",readinessChecks:{},blockerFlags:[],riskFlags:[],sourceRefs:[],dryRunGuard:{dryRunMode:"governance_guard_only",executionSimulationEnabled:false,moneyMovementSimulationEnabled:false,providerSimulationEnabled:false,ledgerSimulationEnabled:false,refundSimulationEnabled:false,fileGenerationSimulationEnabled:false,guardReason:"t",nextAllowedPhase:"11"},executionBoundary:b,createdByAdminId:"a",createdAt:"2025-01-01T00:00:00Z",updatedAt:"2025-01-01T00:00:00Z",archivedAt:null}).success).toBe(false)}));
  });
});
